### ISSUE TITLE
UART doesn't work as expected, halts when input is longer

### ISSUE THREAD

**Issue by bosnivan** [Microsoft/pxt-microbit#732] opened 2018-04-09 20:59 UTC
Hi,

I reported this to _microbit-community.slack.com_ and nobody responded. I'm not sure are they real issues or just some misunderstanding.

This code doesn't work:

```
let buffer: Buffer = null

serial.onDataReceived(serial.delimiters(Delimiters.Hash), () => {
    led.toggle(0, 0)
    buffer = serial.readBuffer(21)
    basic.showNumber(buffer.length)
})
```

I saw some 20 octet limit for BT UART, but nothing for normal. This code toggle LED and then blocks. If I put <=20, it works.

This code also doesn't work as expected:

```
serial.onDataReceived(serial.delimiters(Delimiters.Dollar), () => {
    while (true) {
        buffer = serial.readBuffer(1)
        data = buffer.getNumber(NumberFormat.Int8BE, 0)
        if (data == 36) {
            break
        } else {
            basic.showString(String.fromCharCode(data))
            basic.pause(500)
        }
    }
})
let buffer: Buffer = null
let data: number
```

In this case I tried reading byte by byte. Again there's strange behaviour. For example, when input is _1234567890123456789012345$_ micro:bit will show 21 chars and then block until new data is entered (he'll skip _2345_ from previous entry).

**Comment by abchatra** [comment] 2018-07-06 16:44
This is duplicate of https://github.com/Microsoft/pxt-microbit/issues/767 and we are going to track that.

**Closed by abchatra** 2018-07-06 16:44 UTC
Labels: question, serial view
