### ISSUE TITLE
Special Characters in filenames

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt-microbit#828] opened 2018-05-31 04:15 UTC
Reported by a user and successfully reproduced.
- In Chrome and Firefox
- Name a program with a special character like a comma "Hello, Hello"
- Drag file to Micro:bit
Nothing happens

**Comment by abchatra** [comment] 2018-07-06 17:09
This is duplicate of https://github.com/Microsoft/pxt-microbit/issues/906

**Closed by abchatra** 2018-07-06 17:09 UTC
Labels: P2, bug
