### ISSUE TITLE
Some blocks were not translated when changing language to "Chinese (Simplified)"

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#944] opened 2018-07-10 06:04 UTC
**Repro steps:**
• Navigate to https://makecode.microbit.org/alpha#editor
• Click "More..." -> "Language" -> choose "Chinese (Simplified)"
• Click "无线" and observe

**Expected result:**
All of the blocks should be translated
**Actual result:**
Some blocks were not translated
![issue71001](https://user-images.githubusercontent.com/23466737/42492022-f4b9c556-8449-11e8-9857-fcf3205c701c.PNG)

**Comment by abchatra** [comment] 2018-07-10 16:07
Duplicate of https://github.com/Microsoft/pxt-microbit/issues/907

**Closed** 2018-07-10 16:08 UTC
Labels: localization
