### ISSUE TITLE
Ignore curly braces in Headings of web page view of tutorials

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#5379] opened 2023-10-23 17:40 UTC
In the markdown for tutorials, we’ve been using the {Step 1} notation to not actually show “Step 1” as the header since we have the top nav bar.  
https://makecode.microbit.org/#tutorial:/projects/step-counter
<img width="960" alt="Tutorial View" src="https://github.com/microsoft/pxt-microbit/assets/22108954/ff52b437-a60c-48d8-b558-37be12562c6c">

But in the actual web page version of the tutorial, the headers show up as “{Step 1}”.  Is there anything we can do to ignore the curly braces, but keep the headings of the web-rendered version of the markdown?  
https://makecode.microbit.org/projects/step-counter
<img width="946" alt="Web page View" src="https://github.com/microsoft/pxt-microbit/assets/22108954/eb37367d-ab7c-4cf2-aae1-c9f25a4f7e30">

**Comment by ganicke** [comment] 2024-07-29 18:13
@abchatra - Surprised this showed up again. I can't reproduce this and it was supposedly fixed in https://github.com/microsoft/pxt/pull/8671.

**Comment by abchatra** [comment] 2024-07-29 21:32
Fixed

**Closed by abchatra** 2024-07-29 21:32 UTC
Labels: documentation, tutorial
