### ISSUE TITLE
Exponents Are Still Broken

### ISSUE THREAD

**Issue by CaelCoruscare** [microsoft/pxt-microbit#5584] opened 2024-04-09 21:25 UTC
![image](https://github.com/microsoft/pxt-microbit/assets/20887356/6018f22b-bee6-49d3-b221-57afb75eaf93)

In the debugger, the above code results in the same output regardless of which button is clicked. The math under Button A correctly resolves to 9.5499etc, which is rounded to 10 in the function. If Button B is clicked, 9.5 gets rounded to 10 in the function.

But on the microbit, clicking Button A appears to output about 1.0 instead of 9.5499etc

**To Reproduce**
See Example ^

**Expected behavior**
Using an exponent results in an arithmetically correct answer.

**micro:bit version (please complete the following information):**

You can find this information in the lower right hand corner of the back of micro:bit (the side that says BBC micro:bit).
 - Which version of the micro:bit is this relevant to: V2.21

**Desktop (please complete the following information):**
 - OS: Windows & iOS
 - Browser Firefrox, Chrome, and Opera
 - Version Most Recent

**Additional context**
This issue was reported in 2018, here: https://github.com/Microsoft/pxt-microbit/issues/1435

2 years later, it was marked closed and "completed" by @abchatra with no pull requests or branches associated.

A quick Google search shows that it has been repeatedly reported on the forums in the years since then.

**Comment by abchatra** [comment] 2024-07-18 21:02
Lets evaluate for this release and see if there is a easy way to address without increasing the flash size. Atleast for v2.

**Comment by riknoll** [comment] 2024-08-23 17:06
duplicate of https://github.com/microsoft/pxt-microbit/issues/2192

**Closed by riknoll** 2024-08-23 17:06 UTC
Labels: bug, P2
