### ISSUE TITLE
Block editor - String variables not supported

### ISSUE THREAD

**Issue by martincottrell** [Microsoft/pxt-microbit#217] opened 2016-08-22 08:43 UTC
String variables do not seem to be supported. The assignment block does not allow strings to be assigned. 

I need this to also use the name value packets with the radio lib.

**Comment by gingemonster** [comment] 2016-08-23 17:54
Do you mean like this?

https://codethemicrobit.com/fljccs

**Comment by gingemonster** [comment] 2016-08-23 17:59
I think you are right in saying there is not "string" block though in the menu as I added that in the script view first

**Comment by gingemonster** [comment] 2016-08-23 18:27
looks like its already being done but is part of the base pxt library the microbit version depends on:

https://github.com/Microsoft/pxt/issues/18

**Comment by abchatra** [comment] 2016-10-15 01:17
This is duplicate of #72

**Closed by abchatra** 2016-10-15 01:17 UTC
Labels: enhancement
