### ISSUE TITLE
Copy Pasting code adds indent

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3905] opened 2021-03-16 16:17 UTC
**Describe the bug**

Copying the following and pasting into Python mode:

letters = ["A",
    "B",
    "C",
    "D"]
numbers = ["1",
    "2",
    "3",
    "4",]

adds an indent to the second array

![image](https://user-images.githubusercontent.com/31242877/111343127-0816b900-8673-11eb-8733-ad4d7dee29d9.png)

I would expect this to copy and paste respecting the spacing

**Comment by SquareFingers** [comment] 2021-03-19 20:05
Hm.  The post above, appears to me, to be:

\>\>\>

Copying the following and pasting into Python mode:

letters = ["A",
"B",
"C",
"D"]
numbers = ["1",
"2",
"3",
"4",]

<<<

The intent, I believe, is for it to be:

\>\>\>

Copying the following and pasting into Python mode:

```
letters = ["A",
    "B",
    "C",
    "D"]
numbers = ["1",
    "2",
    "3",
    "4",]

```
<<<

**Comment by joshkordek3** [comment] 2021-03-22 02:57
Hmm, it does not happen in my editor, try closing all the editor tabs and then reopening
![Screenshot 2021-03-22 10 54 48](https://user-images.githubusercontent.com/79750252/111934894-4b52ab00-8afd-11eb-9368-e6d0b74a8d6d.png)

**Comment by SquareFingers** [comment] 2021-03-22 18:20
> Hmm, it does not happen in my editor, try closing all the editor tabs and then reopening
> ![Screenshot 2021-03-22 10 54 48](https://user-images.githubusercontent.com/79750252/111934894-4b52ab00-8afd-11eb-9368-e6d0b74a8d6d.png)

Excuse me for asking, but are you following the instructions from the original post from microbit-mark or the instructions in the comment I made earlier?  microbit-mark was trying to be helpful to me in taking my ticket at
https://support.microbit.org/support/tickets/43871
and opening the issue here on GitHub.  However, if you look at the ticket I wrote, it's really not the same as what's in the top post on this page.

**Comment by joshkordek3** [comment] 2021-03-24 00:45
I followed directions from the original.

**Comment by abchatra** [comment] 2021-03-25 23:40
This doesn't repro for me. If it does, please give me the browser information.

**Closed by abchatra** 2021-03-25 23:40 UTC

**Comment by SquareFingers** [comment] 2021-03-26 00:47
> This doesn't repro for me. If it does, please give me the browser information.

As I asked the previous commenter, are you following the instructions from the original post from microbit-mark or the instructions in the comment I made earlier? microbit-mark was trying to be helpful to me in taking my ticket at
https://support.microbit.org/support/tickets/43871
and opening the issue here on GitHub. However, if you look at the ticket I wrote, it's really not the same as what's shown at the top post on this page.
For reference, I just upgraded my Google Chrome browser to Version 89.0.4389.90 (Official Build) (64-bit) and the issue is still present.  I do not know what browser microbit-mark was/is using.

**Comment by SquareFingers** [comment] 2021-03-26 00:59
Never mind.  I opened a new issue, so that it is correctly described at the very top.
https://github.com/microsoft/pxt-microbit/issues/3936#issue-841495121

**Comment by microbit-mark** [comment] 2021-03-26 08:50
Thanks @SquareFingers. Apologies for the confusion. https://github.com/microsoft/pxt-microbit/issues/3905#issue-832976650 no longer repros for me, but #3936 still does

**Comment by SquareFingers** [comment] 2021-03-26 11:00
No worries @microbit-mark !  I reported it on support.microbit, you showed me it's better to put it here on github.  Thank you for that.  We're all good!
