### ISSUE TITLE
Micro:bit not moving to next icon after recording, but sim does

### ISSUE THREAD

**Issue by kiki-lee** [microsoft/pxt-microbit#5163] opened 2023-05-19 17:57 UTC
Using app on iPad.  This happens for both "until done" and "in background".

This program appears to run correctly in the sim, but on the device it never passes the recording stage.

![Microsoft Edge - Microsoft MakeCode for micro-bit 2023-05-19 at 10 46 03 AM](https://github.com/microsoft/pxt-microbit/assets/1633958/01c5621d-70a0-4d9c-af7e-c1f1f93ad734)

![Microsoft Edge - Microsoft MakeCode for micro-bit 2023-05-19 at 10 46 10 AM](https://github.com/microsoft/pxt-microbit/assets/1633958/e8760f31-b271-4f5f-b15d-c68b87bdcb90)

![Screenshot by Dropbox Capture](https://github.com/microsoft/pxt-microbit/assets/1633958/39ac478d-f432-4c0f-8e3f-122174302d2f)

**Comment by abchatra** [comment] 2023-05-19 17:58
Dupe of https://github.com/microsoft/pxt-microbit/issues/5162. But I will keep this bug as it has more details.

**Comment by kiki-lee** [comment] 2023-05-19 18:01
Ah, that means it's happening on more than the ipad. Good info!

Kim's Repro:

Open https://makecode.microbit.org/_P2fR3zMz6Dsa
Download to microbit
Press A to record, see that recording doesn't stop
makecode.microbit.org version: [5.1.30](https://github.com/Microsoft/pxt-microbit/releases/tag/v5.1.30)
Microsoft MakeCode version: [8.6.39](https://github.com/Microsoft/pxt/releases/tag/v8.6.39)
microbit runtime version: [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)
codal-microbit-v2 runtime version: [v0.2.53](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.53)

**Closed** 2023-05-20 00:22 UTC
Labels: bug, P2, record
