### ISSUE TITLE
Shows 'every NaN ms'  when open 'every 500 ms' help documentation

### ISSUE THREAD

**Issue by v-katherine** [microsoft/pxt-microbit#5662] opened 2024-05-10 02:26 UTC
**Describe the bug**
Shows _'every **NaN** ms'_ when open _'every 500 ms'_ **help documentation**
 
**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2.Create or open a project, blocks, JavaScript and Python project.
3.Toolbox->Loops->**'every 500 ms'** block, **open** the block's **help documentation**.
 
**Actual behavior:**
Shows 'every NaN ms'.
 
**Expected behavior:**
Shows 'every 500 ms' in the help documentation.
 
**Screen Recording:**
![NaN](https://github.com/microsoft/pxt-microbit/assets/148834117/4ece83ef-2f76-41b8-9a77-9496f1577dcc)

**Additional context:**
1.OS: Windows11, iMac Ventura 13.6.6
2.makecode.microbit,org version: 7.0.9
3.Microsoft MakeCode version: 10.0.21

**Comment by abchatra** [comment] 2024-07-25 22:07
Probably dupe of the NaN bug in teacher tool.

**Comment by riknoll** [comment] 2024-08-22 16:37
no longer repros. i'm guessing i fixed this with https://github.com/microsoft/pxt/pull/10061

**Closed by riknoll** 2024-08-22 16:37 UTC
Labels: bug, P2

**Comment by fionama100** [comment] 2024-08-23 08:50
I verified this bug in the latest version: 7.0.22 and it has been fixed.
![Fixed](https://github.com/user-attachments/assets/5776d74a-8f9d-4263-a651-8ce3ff6c55fb)
