### ISSUE TITLE
"Publish Project" doesn't work for code that cannot be represented as Blocks

### ISSUE THREAD

**Issue by eric-camplin** [Microsoft/pxt-microbit#153] opened 2016-06-27 16:30 UTC
any code that cannot convert to blocks shows as reverted to the previous block friendly version  - see this when using the embed feature and fork to view code

**Comment by darrenge** [comment] 2016-06-27 23:11
Might be a duplicate of #149

**Comment by eric-camplin** [comment] 2016-06-27 23:17
The difference is that I don't expect the code to convert back to blocks, but I do expect code  to publish fore sharing in TypeScript format (no blockly)

**Comment by mmoskal** [comment] 2016-07-20 16:03
You can remove 'main.blocks' from the file list (by editing pxt.json). I agree this is not perfect...

**Comment by mmoskal** [comment] 2016-07-21 08:44
@pelikhan @tballmsft - we need to have a way of dropping blocks from project. There is also currently no way of starting a project without blocks.

**Comment by mmoskal** [comment] 2016-08-26 11:24
I think it is fixed now

**Closed by mmoskal** 2016-08-26 11:24 UTC
Labels: bug

**Comment by eric-camplin** [comment] 2016-08-26 16:05
Nicely done - tested working: [https://codethemicrobit.com/fgatsxwpcd](https://codethemicrobit.com/fgatsxwpcd)
