### ISSUE TITLE
Comments rule only seems to apply to block comments

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#5661] opened 2024-05-09 23:51 UTC
Repro - 
Add the Comments Exist rule
Run it against a program with a Workspace comment
Fails the rule
![image](https://github.com/microsoft/pxt-microbit/assets/22108954/b68cc581-6b40-466d-a757-095fa2ca9202)

**Comment by abchatra** [comment] 2024-07-25 22:07
Dupe of https://github.com/microsoft/pxt-microbit/issues/5607

**Closed by abchatra** 2024-07-25 22:07 UTC
Labels: enhancement, code checker tool
