### ISSUE TITLE
Our main package "Giggle" is no longer getting served

### ISSUE THREAD

**Issue by CleoQc** [Microsoft/pxt-microbit#1758] opened 2018-12-26 15:28 UTC
Dec 26th and our main package no longer shows up in the search feature.
If you search for Giggle, two extensions should appear but only the the bluetooth one shows up, not the main one.
Last time we changed anything was 2 weeks ago and it was working fine then. The package can be loaded manually but of course clients don't have the direct URL.
I have confirmed with one client that it was working yesterday, both in being served by makecode and in functionality.

**Comment by CleoQc** [comment] 2018-12-27 15:21
@abchatra  Any ETA on this? It's currently rendering our product unusable. Right after Christmas, when many kids got one as a gift. Really bad timing.

**Comment by abchatra** [comment] 2018-12-27 21:35
This is due to throttling by Github as it is limiting the search to first x packages. We are working on resolving the same. I will let you know the ETA when we know how to fix the issue.

**Comment by CleoQc** [comment] 2018-12-27 22:57
Thanks @abchatra 
If it's Github throlling that's the issue, would it help if we reverse the order of our two extensions?
The `giggle` extension (which is not appearing right now) is much more important than the `gigglebot` extension.  In fact, the `giggle` extension will automatically load up the `gigglebot` one. What we would lose is the contextual help for the `gigglebot` blocks. Would it work ?
if not, can we temporarily disable the `gigglebot` extension so the only extension would be `giggle`?

**Comment by abchatra** [comment] 2018-12-27 23:47
@CleoQc this should be back up. Can you check?

**Comment by abchatra** [comment] 2018-12-27 23:48
We haven't checked the root cause of the issue though. So keep an eye at this and let me know how it goes. Sincere apologies.

**Comment by CleoQc** [comment] 2018-12-28 00:00
thank you sincerely for the help on this. Yes it is indeed back up.
However my question remains. If this is going to potentially happen again, which trick can be used to force the system to pick the `giggle` extension instead of the `gigglebot` one?
In fact, this is a question I've been wanting to ask for a while. How can we make sure `giggle`  shows up first (aka the left entry), and then `gigglebot` ?

**Comment by abchatra** [comment] 2018-12-28 19:43
@CleoQc We can remove gigglebot from the list of approved packages and this would let just only giggle package to show up. Dependency will load up correctly always. Do you want to do that? 

Order is based on the search results GitHub returns and we have no control on it today. We are working on making it better.

**Closed by abchatra** 2018-12-28 19:43 UTC
Labels: P1, bug, next-release

**Comment by CleoQc** [comment] 2018-12-29 01:05
@abchatra  
That was the original plan, to have only the `giggle` extension show up. However, most of the blocks are actually in the `gigglebot` extension, and if it's not an official package, then the help (through the right click popup menu) is unreachable.
The structure is that most of the robot blocks are in `gigglebot` and all the blocks that are incompatible with bluetooth get loaded through the `giggle` extension.
Bluetooth users can load `gigglebot` directly, but the user-friendly blocks that use radio or neopixels are in `giggle`. That's why it's split in two. 
We would be fine with hiding `gigglebot` but not when it means the blocks no longer get contextual help.

**Comment by messwright** [comment] 2019-08-22 14:51
Still no resolution to this?

**Comment by messwright** [comment] 2019-08-22 14:59
nevermind! Though the extension doesn't come up in MakeCode search of "giggle" or "gigglebot," it will come up if you search exactly "pxt-giggle"

**Comment by mrwoods55** [comment] 2019-10-13 21:40
As of OCt 13 - the giggle extension can not be loaded. The giggle extension with Bluetooth remote blocks will not load.

**Comment by abchatra** [comment] 2019-10-14 01:40
@mrwoods55  file issue on that extension repo. https://github.com/DexterInd/pxt-giggle 
@CleoQc
