### ISSUE TITLE
Decimal numbers should display better

### ISSUE THREAD

**Issue by rhubarbdog** [Microsoft/pxt-microbit#1766] opened 2018-12-28 12:04 UTC
**Describe the bug**
Block `basic.showNumber()` should pretty print floating point numbers.
The simulator shows `99.9` as 99.9 but my microbit shows it as 99.900000000000002

**To Reproduce**
these <a href="https://makecode.microbit.org/_cexdRAU70W0L">blocks</a> and the attached .hex file reflect the problem
 
[microbit-float_bug.hex.txt](https://github.com/Microsoft/pxt-microbit/files/2714805/microbit-float_bug.hex.txt)

**Expected behavior**
All decimals should be printed to a reasonable number of decimal places, in the case of
99.9 it should probably by just one

**Desktop (please complete the following information):**
 - OS: Linux mint 18.2
 - Browser mozilla firefox
 - Version 63.0.3

**Comment by abchatra** [comment] 2019-03-15 05:42
Closing as duplicate of https://github.com/Microsoft/pxt-microbit/issues/1781

**Closed by abchatra** 2019-03-15 05:42 UTC
Labels: P2, bug
