### ISSUE TITLE
"Crashy Bird" show errors when switching to "Blocks" and can't run on hardware

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1866] opened 2019-02-27 06:39 UTC
**Describe the bug**
"Crashy Bird" show errors when switching to "Blocks" and can't run on hardware

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/projects/crashy-bird copy this project
2. Navigate to https://makecode.microbit.org/beta#editor and switch to "JavaScript" and paste this project
3. Click "Blocks" and observe
4. Download "Crashy Bird" and copy .hex file to hardware

**Expected behavior (on live site)**
"Crashy Bird" should not show error when switching to "Blocks"
![issue227001com](https://user-images.githubusercontent.com/23466737/53470669-45647a00-3a9d-11e9-9ed2-73458cb84973.gif)

**Actual behavior (on beta site)**
Issue1: "Crashy Bird" show errors when switching to "Blocks"
Issue2: "Crashy Bird" can't run on "Micro: bit" hardware
![issue227001](https://user-images.githubusercontent.com/23466737/53470594-151cdb80-3a9d-11e9-8299-47f857b98c27.gif)

**Additional info:**
This bug only repro on beta (download .hex form beta and drag this file to hardware)

**Comment by Helen09** [comment] 2019-02-27 10:01
"Micro: coin" also can't switch from "JavaScript" to "Blocks" on beta

**Comment by pelikhan** [comment] 2019-03-21 16:02
Shorter repro: 
```
let bird = game.createSprite(0, 2)
bird.set(LedSpriteProperty.Blink, 300)
```

**Comment by pelikhan** [comment] 2019-03-21 16:06
This bug is probably a duplicate of https://github.com/Microsoft/pxt-microbit/issues/1865 (uses a mutable image)

**Closed** 2019-03-21 17:19 UTC
Labels: P2, bug, next-release
