### ISSUE TITLE
W10 App: Serial data export only exports currently visible data

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt-microbit#673] opened 2018-02-23 03:28 UTC
I hope I'm using this feature right - but this behaviour seems a bit odd
The 'export' button on the serial data view in MakeCode W10 app is great for using the micro:bit in science lessons and visualising live data

However, in it's current form it's hard to use for longer running experiments because any numerical data seems to be 'eaten' by the graph (IE it doesn't go to any other log). The graph is constantly scrolling, so after some time any collected data has scrolled off the edge of the page and is lost, as far as I can tell.

I think the 'export data' button should either
* Let the user select a time range
* Export all data from the beginning of time for that app

The current format is quite confusing as you have to 'catch' the data on the graph before it's too late.

**Comment by abchatra** [comment] 2018-02-23 18:32
@pelikhan this is the one we fixed in master right? Can you see if this is ported to v0?

**Comment by jaustin** [comment] 2018-03-07 13:57
@abchatra I think this is fixed now - do we have a good way of managing the closing of tickets in pxt-microbit that are fixed with merges into v0 on pxt? Seems like there's a risk of getting lots of open-but-fixed tickets here?

**Comment by abchatra** [comment] 2018-03-07 16:17
Person who is fixes the issue is responsible closing the issue. @pelikhan do you know who fixed this?

**Closed** 2018-03-07 16:17 UTC
Labels: P2, bug

**Comment by pelikhan** [comment] 2018-03-07 16:34
Can't remember. Use blame.
