### ISSUE TITLE
Can’t load documentation after clicking reference in Win10 offline use of Electron app

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#3251] opened 2020-06-11 09:55 UTC
**Describe the bug**
Can’t load documentation after clicking reference in Win10 offline use of Electron app

**Steps to reproduce the behavior**
1.Open Microbit app
2.New Project
3.Click Reference--->click input

**Expect behavior**
Load documentation after clicking reference
![1](https://user-images.githubusercontent.com/59192069/84371684-9d7cac80-ac0c-11ea-893e-f6413b68389d.gif)

**Actual behavior**
Can’t load documentation after clicking reference
![reference](https://user-images.githubusercontent.com/59192069/84371651-8fc72700-ac0c-11ea-8d0a-f7ed70a4ccff.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.0.10
3.Microsoft MakeCode version: 6.0.11

**Comment by abchatra** [comment] 2020-06-11 15:13
Duplicate of https://github.com/microsoft/pxt-microbit/issues/2202

**Closed by abchatra** 2020-06-11 15:13 UTC
Labels: P2, bug, docs, offline
