### ISSUE TITLE
"Course ": Some cards name has missing in Polski Language

### ISSUE THREAD

**Issue by Ramanan0530** [microsoft/pxt-microbit#5812] opened 2024-08-12 02:52 UTC
**Describe the bug**
"**Course** ": Some cards **name** has missing in **Polski** Language

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta
2. Switch language to **Polski.**
3. Move to **course** section and **compare** with **English** home page.

**Actual behavior**
There is **missing name** of some cards in Course section when switch to Polski Language

**Expect behavior**
Every card name should be appeared normally when switch language.

**Screenshot:** 
![polski](https://github.com/user-attachments/assets/0d936e28-3ef2-452b-ab11-4952fbce42fa)

**Additional context**
1.OS: Windows 11 , MAC
2.Browser: Edge, Firefox, Chrome, Safari
3.makecode.microbit,org version: 7.0.17
5.Microsoft MakeCode version: 10.2.6

**Comment by jwunderl** [comment] 2024-08-12 17:21
This was caused by a mistranslation on crowdin:

![image](https://github.com/user-attachments/assets/fa6ccb7a-e3dd-42a9-a93f-4fe8e6f96eac)

the key in the json fields for name and description was getting translated to 'nazwa' and 'opis', so they effectively don't get set for the rendering code. I've updated the translations, but @ganicke in case you see this elsewhere ~

The translations should be fixed in ~48 hours, but if you've already visited the page may stay for about a week -- will need to check in a private browsing window & clear cache if it goes through.

**Closed by jwunderl** 2024-08-12 17:21 UTC
Labels: localization, crowdin

**Comment by fionama100** [comment] 2024-08-19 03:04
I verified this bug in the latest version: 7.0.20 and it has been fixed.
