### ISSUE TITLE
Logic and Basic block colors are too similar

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#1679] opened 2018-11-29 04:30 UTC
Logging this issue reported by Lisa Anne Floyd on Twitter:

"I'm wondering if in the next iteration, they might consider making the logic and basic blocks more contrasting in colour. It's hard to see that they are from different "drawers" on my slides (e.g., when I have an if.. then inside a forever block as we check the light level)."

**Comment by abchatra** [comment] 2018-11-29 15:54
![image](https://user-images.githubusercontent.com/6107272/49233949-f0389f80-f3ab-11e8-86be-8a573906da03.png)
They look pretty different to me. Is this related to color blindness issue?

**Comment by abchatra** [comment] 2018-11-29 15:54
@samelhusseini

**Comment by nielsswinkels** [comment] 2018-12-10 09:20
Or could it be an issue depending on which screen is used to look at it? I once gave a presentation on a projector that had such horrible colors that everything looked the same.

**Comment by abchatra** [comment] 2018-12-10 17:37
Projectors have issues with color rendering and it is plausible theory. I am closing this as not enough information .

**Comment by abchatra** [comment] 2018-12-12 18:14
Accessibility from NYC schools
-	Accessibility concerns with the new block UI (mainly for visual impairment)
-	No white spaces between blocks - difficult for students to distinguish between different blocks of the same category
-	Some of the block colors very similar (Basic/Logic and Inputs/Radio) - on projectors or bad screens this becomes a problem
-	Is there a way to turn on the yellow block outline highlighting on all blocks?  Maybe in the High contrast mode?  This would help emphasize the shape of the blocks better for students who can't see the colors.

**Comment by samelhusseini** [comment] 2018-12-12 18:16
Yellow block outlining is turned on for all normal blocks. You can't really select a shadow block as you can't drag it out or delete it, and that's the point of the highlighting: to let you know what block will be deleted if you hit backspace, and which block you're currently interacting with.

**Comment by jwunderl** [comment] 2019-09-03 23:12
duplicate of https://github.com/microsoft/pxt-microbit/issues/798

**Closed by jwunderl** 2019-09-03 23:12 UTC
Labels: accessibility
