### ISSUE TITLE
WebUSB indication on microbit

### ISSUE THREAD

**Issue by DaveAtKitronik** [microsoft/pxt-microbit#3675] opened 2020-11-12 15:19 UTC
Flashing a microbit via drag and drop causes the status LED to flash (Yellow one) on V1 and V2.
Flashing via paired WebUSB does not cause the LED to flash - to the extent I wondered if it had actually flashed the micro:bit with the new code

**Comment by microbit-carlos** [comment] 2020-11-12 15:23
Is this only a V2? What version of DAPLink have you got in that board?

**Comment by DaveAtKitronik** [comment] 2020-11-12 15:26
My V1.5 flashes, but the V2 doesnt. This is the V2 Details.txt:
[DETAILS.TXT](https://github.com/microsoft/pxt-microbit/files/5531532/DETAILS.TXT)

**Comment by microbit-mark** [comment] 2020-11-12 15:27
This reproduces for me when flashing via webUSB. Serial output still flashes the LED

```
# DAPLink Firmware - see https://mbed.com/daplink
Unique ID: 9904360249624e45003c601400000034000000009796990b
HIC ID: 9796990b
Auto Reset: 1
Automation allowed: 0
Overflow detection: 0
Incompatible image detection: 1
Page erasing: 0
Daplink Mode: Interface
Interface Version: 0255
Bootloader Version: 0255
Git SHA: 1436bdcc67029fdfc0ff03b73e12045bb6a9f272
Local Mods: 0
USB Interfaces: MSD, CDC, HID, WebUSB
Bootloader CRC: 0x828c6069
Interface CRC: 0x5b5cc0f5
Remount count: 1
URL: https://microbit.org/device/?id=9904&v=0255
```

**Comment by microbit-mark** [comment] 2020-11-12 15:40
This works for me when performing a full flash via webUSB, but not a partial flash

**Comment by microbit-carlos** [comment] 2020-11-12 15:42
Yeah, for a full flash (for example, when a MicroPython programme is in the microbit) the LED flashes, but it doesn't for partial flashing.

**Comment by abchatra** [comment] 2020-11-12 17:32
This is not a blocking bug right?

**Comment by DaveAtKitronik** [comment] 2020-11-13 08:01
I don't think its blocking, but it does cause confusion. 
In my case I was chasing why something didn't work, and it looked like the alterations I had made to the code didn't make it to the microbit - they didn't have the effect I expected (because the problem was not quite what I thought).
For me its annoying, but for an inexperienced person it could be very mystifying, especially as there is a push to use the WebUSB method in general.

**Comment by pelikhan** [comment] 2021-03-25 08:42
@abchatra DAPLink controls that LED, it's not clear what can be done on the MakeCode side.

**Comment by abchatra** [comment] 2021-03-29 16:40
This needs to be fixed in Daplink @jaustin @carlosperate what can be done here? Where this bug should go?

**Comment by microbit-carlos** [comment] 2021-03-29 16:52
Like captured here, if you have any additional information that could help debug this issue in DAPLink it'd be great if you could add it to this ticket: https://github.com/ARMmbed/DAPLink/issues/714

**Comment by abchatra** [comment] 2021-03-29 16:55
Thanks @microbit-carlos . I am closing the issue on the makecode side as this is already tracked in the daplink repo.

**Closed by abchatra** 2021-03-29 16:55 UTC
Labels: P2, bug, webusb
