### ISSUE TITLE
 "Snap the dot" sprite doesn't move on Micro: bit hardware

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1863] opened 2019-02-26 10:27 UTC
**Describe the bug**
 "Snap the dot" sprite doesn't move on Micro: bit hardware

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta
2. Open tutorial "Snap the dot" in "Games" and drag blocks as tutorial
3. Click "Download" and copy this .hex file to hardware

**Expected behavior (on live site)**
![issue22603](https://user-images.githubusercontent.com/23466737/53405862-b8b1b180-39f3-11e9-8a17-84d9fc80cd03.gif)

**Actual behavior (on beta site)**
 "Snap the dot" sprite doesn't move on Micro: bit hardware

**Additional info:**
This bug only repro on beta (download .hex form beta and drag this file to hardware)

**Comment by johan-gorter** [comment] 2019-03-11 08:14
I have the same issue. My micro:bit does show the first two moves, but the 'bounce off the wall' instruction seems to make it crash.

**Comment by pelikhan** [comment] 2019-03-21 16:07
This bug is probably a duplicate of https://github.com/Microsoft/pxt-microbit/issues/1865 (uses a mutable image)

All games are broken on /beta right now.

**Closed** 2019-03-21 17:57 UTC
Labels: P2, bug, next-release
