### ISSUE TITLE
In Fireflies project blocks are not loading in Japanese

### ISSUE THREAD

**Issue by abchatra** [microsoft/pxt-microbit#4439] opened 2021-12-06 05:20 UTC
**To Reproduce**
1. Click on FireFly [tutorial](https://makecode.microbit.org/projects/fireflies)
2. Change the language to Japanese

**Expected behavior**
Blocks load 

**Screenshots**
Blocks don't load

**Comment by abchatra** [comment] 2021-12-06 05:21
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/6107272/144791591-2843c19d-001c-452d-9987-6acf7722691d.png">

**Comment by abchatra** [comment] 2021-12-06 05:21
@dmonroym fyi

**Comment by abchatra** [comment] 2021-12-06 05:24
Subject: [EXTERNAL] A Question on showing blocks

 
Dear Sir or Madame
 
 
Hi. My name is Koji from Japan. I am a teacher at a local computer science school for kids.
It seems I am facing a technical problem in reading a web page in a specific part in micro:bit section of the Make Code website. Could you help me in solving this problem?
 
I started a new tutorial page today, and found this problem. The problem is that I cannot see coding blocks as the Microsoft had intended. The place where the problem is happening is in ‘how to use’ page in ‘Fireflies’ in ‘Radio Games section’. There is a white blank where there should be picture of coding blocks. I just see corrupt texts when I highlight a white space.
I paste a link to the page where I am facing the problem.
 
https://makecode.microbit.org/projects/fireflies
(I showed the page in Japanese.)
 
I know this is a kind of error, since I watched a video titled ‘Firefly’, a tutorial, where coding blocks are showed in the way as showed in other tutorial pages.
 
I am looking forward to hearing from you.
Thank you.
 
 
*******************************************

**Comment by ganicke** [comment] 2021-12-06 22:43
The package spec for `radio` was inadvertently translated. Tested this out on local serve by switching `radio` with `無線`  and was able to reproduce the problem. The rest of the page render will bomb out due to not resolving the `無線` package.

The translation fix is in https://crowdin.com/translate/kindscript/1438/en-ja?filter=basic&value=3

**Comment by ganicke** [comment] 2021-12-06 23:28
Render works again, yeah!

![image](https://user-images.githubusercontent.com/27789908/144938997-8d9dbd44-5e07-4e09-866d-9bcaf51bd420.png)

**Closed by ganicke** 2021-12-06 23:28 UTC
Labels: documentation, localization

**Comment by dmonroym** [comment] 2021-12-06 23:53
Thanks @ganicke! I'm finishing up updated docs for people that are translating these so they stop breaking

**Comment by abchatra** [comment] 2021-12-07 02:44
Thanks so much @ganicke

**Comment by ganicke** [comment] 2021-12-09 00:09
@dmonroym, @abchatra  - The problem is that there is no context for the package string. Can we tell the translators that they should leave a seemingly random placement of a word at the end of the page alone? If it was a full path it might be more obvious.

The document view makes the string look like it needs translation:

![image](https://user-images.githubusercontent.com/27789908/145309776-e86e1535-1268-44e0-bd7d-9e4523d74b72.png)

There is nothing but the string in editing pane so it feels like it should get translated:

![image](https://user-images.githubusercontent.com/27789908/145310156-89aea101-7f3d-4cbb-8fc0-3cd2c1e62abb.png)

I recommend that we escape the 'target local' package/extension name somehow:

````
```package
^radio
```
````

That way it would end up looking tagged and we can direct them to it as something specific not to translate.

**Comment by dmonroym** [comment] 2021-12-09 00:33
@ganicke Oh that's a great catch. I've been trying to go over the special strings in tutorials and skillmaps to add to the documentation but escaping these packages might be the right way of doing it - perhaps it might require extra work to go back and change the currently existing ones but I'll discuss with the team.

**Comment by abchatra** [comment] 2021-12-09 05:12
We already have ```package tag right, how removes those?
