### ISSUE TITLE
Documentation disappears from the origin page if opening documentation in new tab

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4140] opened 2021-06-07 09:54 UTC
**Describe the bug**
Documentation disappears from the origin page if **opening documentation in new tab**

**Steps to reproduce the behavior**
1.Nabigate to https://makecode.microbit.org/beta#
2.Blocks To JavaScript---->Hello JavaScript------>Show Instructions
3.Open documentation in new tab and return the origin page

**Actual behavior**
Documentation disappears from the origin page if **opening documentation in new tab**
![2](https://user-images.githubusercontent.com/59192069/120996718-2941fe00-c7b9-11eb-9b49-7edff5cf74d9.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.87
3.Microsoft MakeCode version: 6.13.42

**Comment by abchatra** [comment] 2021-06-07 16:28
This is intentional. User is saying pop out the documentation as separate tab instead of in the editor. Closing as by design.

**Closed by abchatra** 2021-06-07 16:28 UTC
