### ISSUE TITLE
Shift/Rotate pixels breaks neopixel program

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1705] opened 2018-12-06 14:42 UTC
**Describe the bug**
When using the rotate or shift pixel block within a program that uses neo pixels, the program seemingly does not run properly on the micro:bit. Removing this block enables the device to work again. This isn ot an issue in v0

**To Reproduce**
1. Go to https://makecode.microbit.org/_K16egV7yLMVK
2. Download and flash file. See issue
3. Remove rotate pixel block
4. DOwnload and flash file. Do not see issue.

**Expected behavior**
Neopixel should work as in v0 eg https://makecode.microbit.org/_APH0MWFfYTmg works

**Desktop (please complete the following information):**
 - OS:Mac
 - Browser Firefox
 - Version 63

**Smartphone (please complete the following information):**
Not tested

**Additional context**
This thread in Slack offers some differing experiences. I can recreate the issue whilst another user cannot.https://microbit-community.slack.com/archives/C226FGXQX/p1544103101013500?thread_ts=1544093253.012700&cid=C226FGXQX
I'm using a 10 LED pixel edge device for testing.

cc @DaveAtKitronik

**Comment by microbit-carlos** [comment] 2018-12-20 18:20
I can confirm this is related to #1631 (DAPLink 0234 and hex files writing to RAM after end-of-file record).

I've taken the original hex and loaded into a 0234 micro:bit, no fail message given, neopixels don't work.
Then, I manually removed the data after the end-of-file record, loaded that hex file and it works fine.
[hex-files.zip](https://github.com/Microsoft/pxt-microbit/files/2700005/hex-files.zip)

**Comment by abchatra** [comment] 2019-03-15 04:30
Dupe of https://github.com/Microsoft/pxt-microbit/issues/1631

**Closed by abchatra** 2019-03-15 04:30 UTC
Labels: from micro:bit support
