### ISSUE TITLE
Music documentation page loads block preview but does not display blocks

### ISSUE THREAD

**Issue by JacobBovee** [microsoft/pxt-microbit#2098] opened 2019-05-29 21:34 UTC
**Describe the bug**
Music intro reference page (https://makecode.microbit.org/reference/music) does not render blocks that are in the markdown. 

**To Reproduce**
1. Go to https://makecode.microbit.org/reference/music

**Expected behavior**
Should load a number of blocks that can be found in the music.md.

**Screenshots**

Loading:
![image](https://user-images.githubusercontent.com/6301646/58592830-32894f00-821e-11e9-8f8e-2d8d256accf0.png)

After loading:
![image](https://user-images.githubusercontent.com/6301646/58593108-ee4a7e80-821e-11e9-8b4f-ae126ee5ca4e.png)

**Desktop (please complete the following information):**
 - OS: Chrome OS
 - Browser: Chrome

**Additional context**
It generally seems like the intro Music documentation may seems small.

**Comment by jwunderl** [comment] 2019-05-29 21:36
As we figured out the issue offline: this will be fixed with the update, as the issue is that this block https://github.com/microsoft/pxt-microbit/blame/master/docs/reference/music.md#L10 doesn't exist in the live site but does in /beta

**Comment by jwunderl** [comment] 2019-06-18 18:01
Fixed~

**Closed by jwunderl** 2019-06-18 18:01 UTC
