### ISSUE TITLE
The code page can't load completely on Edge

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1213] opened 2018-09-12 03:25 UTC
**Repro steps:**
1. Navigate to https://makecode.microbit.org/projects/reaction-time
2. Scroll down the scroll bar and click "Code"
3. Scroll down the scroll bar and observe the page

**Expected result(Chrome, Firefox & IE):**
The code page should can load completely

**Actual result:**
The code page can't load completely on Edge
![issue91201](https://user-images.githubusercontent.com/23466737/45400298-30766480-b67e-11e8-9176-8a241ce4dbb3.gif)

**Test Info:**
OS : rs4_release.180410-1804.17131.1.amd64fre
**Browser:**
**Edge:** 42.17134.1.0

**Comment by abchatra** [comment] 2018-09-12 16:42
This is duplicate of https://github.com/Microsoft/pxt-adafruit/issues/780 
Edge performance issue with variables.

**Closed by abchatra** 2018-09-12 16:42 UTC
