### ISSUE TITLE
code not rendering... catch the egg game 

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/pxt-microbit#35] opened 2016-04-01 00:57 UTC
the code works in the simulator, but not rendering

open KSF, enter this in JS

```
let basketX = 2
let eggX = 2
let eggY = 0
basic.forever(() => {
    led.unplot(basketX, 4)
    led.unplot(eggX, eggY)
    eggY = eggY + 1
    led.plot(eggX, eggY)
    basic.pause(300)
    let accX = input.acceleration(Dimension.X)
    basketX = 2 + Math.min(2, Math.max(-2, accX / 200))
    led.plot(basketX, 4)
    if (eggY > 4) {
        eggY = -1
        eggX = Math.random(5)
    }
    basic.pause(300)
})
```

here is the lesson

http://localhost:3232/lessons/catch-the-egg-game/activity

**Comment by pelikhan** [comment] 2016-04-13 15:59
Duplicate of #30

**Closed by pelikhan** 2016-04-13 15:59 UTC
Labels: question
