### ISSUE TITLE
W10 App: Soft-bricking of micro:bit when flashing over Python program

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt-microbit#648] opened 2018-02-15 17:12 UTC
Steps to reproduce:
* Go to python.microbit.org and flash a 'hello world' program to your micro:bit
* Open with Windows 10 app
* Flash the micro:bit using the W10 app, any simple icon will do

Expected behaviour:
* Icon is shown

Actual Behaviour:
* micro:bit appears dead. Flashing other programs with the app doesn't work

You can recover your micro:bit by using mass storage Drag and Drop

Here's a hex file from a 'broken' micro:bit
[out.zip](https://github.com/Microsoft/pxt-microbit/files/1728648/out.zip)

**Comment by pelikhan** [comment] 2018-02-15 18:53
I can repro.

**Comment by mmoskal** [comment] 2018-02-15 23:10
This commit https://github.com/Microsoft/pxt-microbit/commit/161444b5d359e6a9c6bf27b7ce6a9de67c7ba78c fails the flashing if we detect problems with UICR; we should be more explicit in asking the user to just drag&drop the file and everything will work the next time.

@jaustin if you have someone who could look into actually fixing this - please go ahead. It seems the problem is writing to the UICR - probably the flash-writing code needs to be updated

**Comment by mmoskal** [comment] 2018-02-15 23:10
It's also possible that codal require some memory to be erased, when it's not.

**Comment by jaustin** [comment] 2018-02-16 09:57
@mmoskal thanks for the workaround. I'm guessing we're hitting problems because the UICR can only be erased with a full erase?

8.1 of the nRF51 Reference Manual
Code readback protection of the whole code area, or a part of the code area can be configured and enabled in the UICR. The UICR can only be erased by using ERASEALL.

**Comment by pelikhan** [comment] 2018-02-16 15:43
The fix is in beta. I've also added a 5th step in the troubleshoot to download a .hex file into the MICROBIT drive.

**Closed by pelikhan** 2018-02-16 15:43 UTC
Labels: P1, Windows App, bug

**Comment by jaustin** [comment] 2018-02-16 16:07
@pelikhan is there a fix beyond this workaround? If not can we spawn a ticket for a real fix to keep track of it?

**Comment by pelikhan** [comment] 2018-02-16 16:10
The fix does not appear to be on our side.

**Comment by mmoskal** [comment] 2018-02-16 16:31
This is a corner case with an easy workaround. 

The fix would he in extension.ts and certainly in reach of someone with DAPLink expertise. PRs are welcome.

**Comment by mmoskal** [comment] 2018-02-16 16:44
Actually, it would be probably best if the partial flashing code moved into dapjs. Then this is also where the fix would be. 

On the record, I did spent a few hours trying to fix this. The UICR BOOTLOADER register contains -1, so it should be possible to just flash it, but somehow it didn't work with regular full-page programming. I guess the real solution would be to detect the abnormal situation, do a full chip erase and flash everything.

**Comment by jaustin** [comment] 2018-02-16 17:21
Okay thanks both

 @mmoskal okay, so to make sure I've understood: you got to the point where you think it's not just simply that we're expecting to write to the UICR without erasing, but that something that *should* work (IE flipping the 1s) that isn't working?

Are the chunks of asm that you've pulled in coming direct from dapjs or pyocd or some other project, or did you write them?

**Comment by mmoskal** [comment] 2018-02-16 17:23
Well, I even think it did write the UICR, this is at least what the GDB says, but still something is wrong.

The machine code comes from here https://github.com/Microsoft/pxt-microbit/tree/master/external/sha
