### ISSUE TITLE
Impossible to create nested loops

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#2864] opened 2020-04-21 04:52 UTC
The loop variable cannot be renamed. It's always index.

![image](https://user-images.githubusercontent.com/4175913/79826647-208e2e80-8351-11ea-8732-7153914621d6.png)

**Comment by abchatra** [comment] 2020-04-21 04:54
This is by design. You can always drag a new variable in.

**Comment by pelikhan** [comment] 2020-04-21 04:56
We used to be able to rename that variable.
![image](https://user-images.githubusercontent.com/4175913/79826885-c2158000-8351-11ea-92ba-e94bddb8788e.png)

**Comment by abchatra** [comment] 2020-04-21 04:58
Yes it is a regression from live.

**Comment by shakao** [comment] 2020-04-22 23:17
Fixed in https://github.com/microsoft/pxt/pull/6892

**Closed by shakao** 2020-04-22 23:17 UTC
Labels: Blocks, P2, bug, next-release

**Comment by jaustin** [comment] 2021-01-12 17:59
@abchatra we discussed this today but this issue isn't quite the same. Do you want to re-open this or make a new issue?

**Comment by abchatra** [comment] 2021-01-12 22:26
New issue would be great. This is not the same.
