### ISSUE TITLE
The score on the hardware flashes very quickly

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2821] opened 2020-04-15 08:54 UTC
**Describe the bug**
The score on the hardware flashes very quickly

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Games---->Snap the dot
3.Start Tutorial
4.Click "Download" 
5.Run it on the hardware

**Expect behavior**
Clear score display as the website
![1](https://user-images.githubusercontent.com/59192069/79318349-715cec00-7f39-11ea-9177-96077fc62617.gif)

**Actual behavior**
The score on the hardware flashes very quickly to make it unclear

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.13
3.Microsoft MakeCode version: 5.37.22

**Comment by abchatra** [comment] 2020-04-15 22:54
@Sheila111  can you see if this is a regression from live? (Check makecode.microbit.org and not beta and see the behavior)

**Comment by Sheila111** [comment] 2020-04-16 01:31
@abchatra  Clear score display on live version

**Comment by abchatra** [comment] 2020-04-16 04:06
Looks like a regression on hardware.

**Comment by pelikhan** [comment] 2020-04-17 04:57
Smaller repro. Delay is broken for single character strings.
```
input.onButtonPressed(Button.A, function () {
    basic.showString("X")
    basic.clearScreen()
})
```

**Comment by pelikhan** [comment] 2020-04-17 15:43
@finneyj @jamesadevine

**Comment by pelikhan** [comment] 2020-04-21 19:44
Fixed in beta.

**Closed by pelikhan** 2020-04-21 19:44 UTC
Labels: P2, bug, device, next-release
