### ISSUE TITLE
Name of approved extension does not honor the name in pxt.json 

### ISSUE THREAD

**Issue by paulobarcelos** [microsoft/pxt-microbit#2596] opened 2020-02-04 14:54 UTC
**Describe the bug**
The name of an approved extension (https://github.com/strawbees/pxt-robotic-inventions) displayed in the search results does not match the name that is registered in the `pxt.json`. Before the extension was approved the name matched the name provided in `pxt.json`

**To Reproduce**
1. Go to extensions search
2. Search for 'strawbees'
3. See that the only result is `robotic-inventions`

**Expected behavior**
The name of the extension should be `Strawbees Robotic Inventions`  as listed in here https://github.com/strawbees/pxt-robotic-inventions/blob/56e6b3724f96bbc1198bb74148ed20a34e53ce10/pxt.json#L2

**Screenshots**
<img width="771" alt="Screenshot 2020-02-04 at 11 16 49" src="https://user-images.githubusercontent.com/122277/73755230-7ab12780-4744-11ea-82cb-1654a383d091.png">
<img width="544" alt="Screenshot 2020-02-04 at 11 51 03" src="https://user-images.githubusercontent.com/122277/73755339-a6cca880-4744-11ea-847d-d22a9fa3db93.png">

**Desktop:**
 - OS: MacOS, Windows
 - Browser: all

**Smartphone:**
 - Not tested

**Additional context**
Interesting that this behaviour didn't happen before the extension was approved. I have specifucally asked about "Where does the name comes from?", in the Makecode official Slack, and got confirmed that name comes from the `name` property in the `pxt.json`. So I tested and even experimented with different names. After the extension was approved, the name changed.

**Comment by pelikhan** [comment] 2020-02-04 19:05
I don't think this ever worked. We do not load the pxt.json of each search result; instead we use the information returned by github.

**Comment by paulobarcelos** [comment] 2020-02-06 14:00
@pelikhan, so you mean that this is really a bug and the name should really come from `pxt.json`? 

The important thing for me is that the name of our extension shows up correctly, so I am willing to do whatever it takes to make it work. But as I am understanding it, if this is a bug on MakeCode, all I need to do is wait, correct?

**Comment by pelikhan** [comment] 2020-02-06 15:13
This is a feature currently. The repo  name is used in the UI because we don’t load the pxt.json.

**Comment by paulobarcelos** [comment] 2020-02-06 16:26
But what I am trying to understand is if MakeCode will load the `pxt.json` on the search at some point soon. Or if I should just change the name of the repo now to make sure we get a better descriptive name.

**Comment by pelikhan** [comment] 2020-02-06 16:28
Change the repo name. It is too expensive to request pxt.json files in each extension repo

**Comment by paulobarcelos** [comment] 2020-02-06 16:34
Ok, good to know! When I change the name, the url of the repo will also change. Will that have any effect on the extension approval, since that seems to be tied to the repo name/url, as you can see in the pull-requests: https://github.com/microsoft/pxt-microbit/pull/2589/files

**Comment by pelikhan** [comment] 2020-02-06 16:36
Yes you have to send a PR to update the name in targetconfig.json

**Comment by pelikhan** [comment] 2020-02-06 21:53
Closed as by design.

**Closed by pelikhan** 2020-02-06 21:53 UTC
Labels: P2, bug, extensions, next-release
