### ISSUE TITLE
Compiled failed,please check your code

### ISSUE THREAD

**Issue by XC16** [microsoft/pxt-microbit#2281] opened 2019-07-18 16:09 UTC
Hi,I got a error whedn i try to download the code.It appear compiled failed,please check you code..Can you help me check this ?I got this error
This my codelink:https://makecode.microbit.org/_6zg5vsKL1iRu

error:
POST https://dc.services.visualstudio.com/v2/track 400 (104: Field 'time' on type 'Envelope' is newer than the allowed max date. Expected: now + 7200000ms, Actual: now + 53989067ms)
t._xhrSender @ ai.0.js:1
t.triggerSend @ ai.0.js:1
(anonymous) @ ai.0.js:1
setTimeout (async)
t._setupTimer @ ai.0.js:1
t.send @ ai.0.js:1
n._track @ ai.0.js:1
n.track @ ai.0.js:1
n.trackEvent @ ai.0.js:1
(anonymous) @ pxtweb.js:83
TelemetryQueue.track @ pxtweb.js:16
aiTrackEvent @ pxtweb.js:85
pxt.tickEvent @ pxtapp.js:95
t.compile @ main.js:83
t.handleClick @ main.js:83
ka @ main.js:758
invokeGuardedCallback @ main.js:758
invokeGuardedCallbackAndCatchFirstError @ main.js:758
Fa @ main.js:758
Ja @ main.js:758
La @ main.js:758
Ha @ main.js:758
Oa @ main.js:758
Pa @ main.js:758
Td @ main.js:758
batchedUpdates @ main.js:758
dc @ main.js:758
Xd @ main.js:758
interactiveUpdates @ main.js:758
Wd @ main.js:758
pxtapp.js:1945 warning: Compilation failed, please check your code for errors.t the bug is.

**Comment by abchatra** [comment] 2019-07-25 17:12
This program seems too big to fit into microbit. 
msg = "program too big by 1620 bytes!"

**Comment by abchatra** [comment] 2019-07-25 17:13
@mmoskal fyi

**Comment by mmoskal** [comment] 2019-07-25 17:18
yup, too big; you could try to encode your melody as buffer or string, you may be able to save these 1.6k that way

**Comment by abchatra** [comment] 2019-07-25 17:23
Closing as by design.

**Closed by abchatra** 2019-07-25 17:23 UTC
Labels: P2, bug, compiler
