### ISSUE TITLE
V2 Neopixel error - Was working prior Christmas

### ISSUE THREAD

**Issue by DaveAtKitronik** [microsoft/pxt-microbit#3825] opened 2021-01-05 11:43 UTC
**Describe the bug**
WS2812B (3535 size) LEDs on Kitronik ZIP64 are no longer working with V2 micro:bit

This zip contains a test hex. It shows a rainbow on startup and then red/blue on a couple of button presses.
[microbit-zip64testwith-icon.zip](https://github.com/microsoft/pxt-microbit/files/5769932/microbit-zip64testwith-icon.zip)

The button presses are registering OK, and on a V1.5 micro:bit the LEDs light as expected. On a V2 micro:bit the button presses register (and the microbit screen shows the icons), but no LEDs in the WS2812 matrix light up.

**micro:bit version (please complete the following information):**
OK on V1.1, 1.3, 1.5
Does not work on V2.00

**Desktop (please complete the following information):**
 - OS: windows10 
 - Browser Edge, but not thought to be browser related.

We tested all this functionality prior to labelling our devices as V1/V2 compatible, and it was working.
We have customers who bought Christmas microbits and accessories which are not functional because of this bug.

Other devices with various WS2812 LEDS on (HaloHD, :MOVE Motor, :MOVE mini) are working as expected on both V1 and V2 microbits. 
As I am working at home I do not have access to an oscilloscope or wider selection of accessory boards, but will try to get someone who is in the office to take a scope trace of the waveform - in case it is a timing issue difference between how V1 and V2 create the hex file sections (not certain if they use the same code base in both, or if the V1 uses the older codebase somehow)

**Comment by microbit-mark** [comment] 2021-01-05 12:39
@abchatra @pelikhan It looks like the last couple of releases relate to changed in pxt-core. Could this have introduced an issue? Is it useful to look back at the last couple of incremental releases eg. https://makecode.microbit.org/v3.1.45 and https://makecode.microbit.org/v3.1.44 to see where the issue was introduced.

**Comment by pelikhan** [comment] 2021-01-05 13:10
You should be able https://makecode.microbit.org/stable instead https://makecode.microbit.org/beta. "beta" is beta and may have regressions.

**Comment by jaustin** [comment] 2021-01-05 15:12
@DaveAtKitronik can you please confirm whether this is a regression on live or beta? I understood from your original issue that this was a regression on Live?

**Comment by DaveAtKitronik** [comment] 2021-01-05 15:32
Live makecode. reported from customer - who is unlikely to be using /beta and then recreated using just makecode.microbit.org
![image](https://user-images.githubusercontent.com/25896029/103665320-3721f780-4f6b-11eb-86fa-2c408facb154.png)

**Comment by jaustin** [comment] 2021-01-06 18:04
@pelikhan any ideas as this is in Live?

**Comment by AlasdairAtKitronik** [comment] 2021-01-07 08:36
I've managed to get a scope, several ZIP64s and several V2 micro:bits, so I'm now able to do some hardware investigation as well. I'll post any updates on that side of things when I get them, but for now, I've firmly established that this is only an issue with the V2 micro:bit - all the product samples work with V1s.

**Comment by jaustin** [comment] 2021-01-07 09:41
@AlasdairAtKitronik as this was working before Christmas, and because we drive WS2818BS quite differently on V1 and V2 I think it'd be best to work out which change caused the breakage. Have you tried the older isntances Mark linked?

**Comment by DaveAtKitronik** [comment] 2021-01-07 11:34
I tried to use older verions, but anything before 3.0.61 doesnt compile:
![image](https://user-images.githubusercontent.com/25896029/103888170-3066c200-50dc-11eb-98fc-789d9295f85e.png)

Output.txt happliy reports: Everything seems fine!

**Comment by microbit-mark** [comment] 2021-01-07 15:55
@DaveAtKitronik https://makecode.microbit.org/stable is at v3.0.63, have you tried that too?

**Comment by DaveAtKitronik** [comment] 2021-01-08 15:07
In looking into this we have noticed that the timings are also suspect on V2. Ill open a separate issue for that.

**Comment by jaustin** [comment] 2021-01-15 18:13
The issue here is that the pin configurations on V1 and V2 by default allow slightly different amounts of current to be sunk through the pin. In this case, the issue can be resolved by setting the P0 to high drive mode using the following API https://github.com/lancaster-university/codal-nrf52/blob/master/source/NRF52Pin.cpp#L895 but it's specificic to the hardware in question. This isn't a general problem with neopixels

**Closed by jaustin** 2021-01-15 18:13 UTC
