### ISSUE TITLE
recording extension: No way to stop recording (without playback)

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#5125] opened 2023-05-10 17:32 UTC
Currently, the only way to stop audio recording is with the playback block:

<img width="563" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/ef33d5c7-454f-4a84-8871-510fea446e34">

> makecode.microbit.org version:  [5.1.26](https://github.com/Microsoft/pxt-microbit/releases/tag/v5.1.26)
> Microsoft MakeCode version:  [8.6.33](https://github.com/Microsoft/pxt/releases/tag/v8.6.33)
> microbit runtime version:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)
> codal-microbit-v2 runtime version:  [v0.2.50](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.50)

I think it might have been mentioned in the past that the `[stop all sounds]` block might be used for this, but trying it in this programme doesn't stop recording either:

[microbit-record (3).hex.zip](https://github.com/microsoft/pxt-microbit/files/11444558/microbit-record.3.hex.zip)

<img width="883" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/9a37fb0d-f299-456c-9ba7-81cb40f40a4d">

Only pressing A+B to playback the recording stops it. We should probably have an explicit block for that, as users might just want to record a couple of seconds without playing them immediately after.

**Comment by srietkerk** [comment] 2023-05-11 20:32
It should with the changes that I pushed in recently, I need to bump beta.

**Comment by microbit-carlos** [comment] 2023-05-12 12:22
The `[stop all sound]` block doesn't fit very well for this purpose, no?

I don't see how the average user might guess that to stop recording they need to get a block from the "Music" toolboox that is called "stop all sound". Specially since recording is an input, and sound is an output.

**Comment by abchatra** [comment] 2023-05-12 15:07
@microbit-carlos by default the record audio block is going to be blocking and it automatically stops at 3 seconds by default settings or when playback is played . So adding stop recording didn't seem important at this point of time. We will add blocks if there are cases. I am closing for now as by design.

**Comment by abchatra** [comment] 2023-05-12 15:08
Blocking part of the record audio is not checked in yet.

**Closed by abchatra** 2023-05-12 15:07 UTC
Labels: bug, P2, record
