### ISSUE TITLE
Full flash needs a progress bar

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#3528] opened 2020-10-30 09:02 UTC
A full flash webusb flash make take a minute or two. We need:'

- [ ] a progress bar
- [ ] cancel button

**Comment by abchatra** [comment] 2021-03-25 06:22
Duplicate of https://github.com/microsoft/pxt-microbit/issues/3927

**Closed by abchatra** 2021-03-25 06:22 UTC
Labels: P2, bug, webusb
