### ISSUE TITLE
Beta: SerialWriteString() & SerialWriteLine() – excessive delay between characters

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#2023] opened 2019-04-25 09:14 UTC
microbit support: 21785

**Describe the bug**
When using SerialWriteString() in a while loop to repeatedly send charcters on the re-directed serial port there is an excessive delay, up to 6ms between charcters output.  The same result is obtained with SerialWriteLine(). All Baud rates exhibit this issue of excessive ~5.63ms inter-character delay.

**To Reproduce**
The effect can be fully appreciated using an oscilloscope connected to P0. 

![DSCN1819](https://user-images.githubusercontent.com/31242877/56724076-32d78b80-6742-11e9-8a3f-10ffe656210f.JPG)
 This shows the output of two successive characters at 9600 Baud. Between each character output there is a 5ms delay making the character repetition rate 6ms. Similar results can be obtained for all other Baud rates.

Test code in Makecode Beta is simple: Within On start = Serial redirection to P0 & P1, baud rate 9600. Followed by while-true loop with SerialWriteString “A” inside. Oscilloscope probe connected to P0. Similar findings can be obtained using SerialWriteLine().

https://makecode.microbit.org/_XryMM1JJxEE0

An appreciation can be obtained without an oscilloscope using the above program. Pressing button A captures the running time, then a single character is written using serialWriteLine(), after which the running time once again is captured. The difference between running time prior to the write and after is then displayed on the LED matrix. Irrespective of Baud rate the value is about 5630us.

It appears that MakeCode only supports the [ASYNC functionality from the DAL](https://lancaster-university.github.io/microbit-docs/ubit/serial/#serial-modes),  as there is no way to pass additional parameters to the DAL serial method calls.

https://github.com/Microsoft/pxt-microbit/blob/fc73d71d638f54e488a66afcaf6727f9a1da44da/libs/core/serial.ts
 and
https://github.com/Microsoft/pxt-microbit/blob/fc73d71d638f54e488a66afcaf6727f9a1da44da/libs/core/serial.cpp

**Expected behavior**
No delay between characters

**Comment by whaleygeek** [comment] 2019-05-02 10:09
I looked at the DAL code with Ed on this, I think 6ms is the DAL fiber scheduler. I looked at the DAL code for ASYNC mode, it will set an event flag for each character and later the fiber scheduler will poll events and process the character. Not a DAL bug, but you may want to look at using different DAL serial modes for what is effectively a blocking MakeCode call? @abchatra comments??

The problem is that this significantly affects the performance of a system when trying to communicate with an external module like a GPRS MODEM. You won't see this timing behaviour via the normal USBSER link that goes over the USB port, due to the interactions that occur with the KL26 interface chip and the host USB stack at the other end. You will only see this undesirable timing behaviour when redirected to the pins.

**Comment by pelikhan** [comment] 2019-06-07 16:01
Related to https://github.com/microsoft/pxt-microbit/issues/1157

**Comment by abchatra** [comment] 2020-03-21 19:22
DAL issue. Closing in our repo

**Closed by abchatra** 2020-03-21 19:22 UTC
Labels: P2, bug, from micro:bit support, serial
