### ISSUE TITLE
Add a Progress indicator for long WebUSB downloads

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#5191] opened 2023-05-26 17:36 UTC
![image](https://github.com/microsoft/pxt-microbit/assets/22108954/0f95a1e6-f496-49ae-8692-5af231969ecb)

**Comment by abchatra** [comment] 2023-05-26 17:40
Dupe of https://github.com/microsoft/pxt-microbit/issues/5093 But will keep it open as other has lot of comments.

**Closed** 2023-05-31 22:32 UTC
Labels: bug, P2, webusb
