### ISSUE TITLE
on shake should show icon and text

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#2689] opened 2020-03-26 23:08 UTC
This should read "on shake"

![image](https://user-images.githubusercontent.com/4175913/77705098-047ab580-6f7c-11ea-9acb-8ba938406bd5.png)

**Comment by abchatra** [comment] 2020-03-26 23:12
Duplicate of issues https://github.com/microsoft/pxt-microbit/issues/2678

**Closed by abchatra** 2020-03-26 23:12 UTC
Labels: next-release
