### ISSUE TITLE
W10 App: Serial data logging only starts once the page is switched to, even though data is available sooner

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt-microbit#674] opened 2018-02-23 03:33 UTC
Consider this program
https://makecode.microbit.org/_fFr2x526mUEP

If I press 'Download' in the W10 app to flash the micro:bit and then press button 'B' when the program starts running the 'Show data (device)' lozenge appears

When I click this, I get taken to a blank page. Even though the app knows I had data, it isn't shown to me, so it looks like no data was sent. This means that we have to revert to putting things like "Wake up serial" there on start to ensure that we can always switch to the right view in order to catch the required event. Furthermore, clicking the 'export' button does nothing.

I think it would be better if the data was stored and then graphed once the view was entered.

**Comment by pelikhan** [comment] 2018-02-23 05:10
We’ve made a change in master that stores the data even when the view is not visible. We need to ensure it is in v0

________________________________

**Comment by abchatra** [comment] 2018-02-23 18:26
@pelikhan can you close this bug when you verify this made into /beta on v0?

**Comment by abchatra** [comment] 2018-02-23 18:29
I think this is by design. We disconnect from the device once we switch away from page. This is the behavior of the WINRT as the underlying objects are garbage collected.

**Comment by abchatra** [comment] 2018-02-23 18:30
You need to be on the serial view page to see the data.

**Comment by abchatra** [comment] 2018-07-04 01:53
This is fixed in alpha

**Closed** 2018-07-04 01:56 UTC
Labels: enhancement
