### ISSUE TITLE
Comments move when sharing project

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#4968] opened 2023-03-02 16:59 UTC
Is this related to comments moving location? e.g. between the editor view when shared:
![image](https://user-images.githubusercontent.com/42380137/222412936-40c672b8-e921-4313-9035-96f783def97a.png)

and the project as opened from shared link:
![image](https://user-images.githubusercontent.com/42380137/222412975-cab5cfcd-7419-4065-b1ef-0f6112f96e66.png)
(comments now obscure blocks, overlapping persists when opened it editor)

_Originally posted by @microbit-giles in https://github.com/microsoft/pxt-microbit/issues/4910#issuecomment-1451702688_

**Comment by abchatra** [comment] 2023-03-02 17:48
I will close this as duplicate of #4910. Lets keep the discussion in that bug and fix it together..

**Closed by abchatra** 2023-03-02 17:48 UTC
