### ISSUE TITLE
Maths function to take floor value of number needed

### ISSUE THREAD

**Issue by bluetooth-mdw** [Microsoft/pxt-microbit#204] opened 2016-08-17 06:31 UTC
I couldn't see a way of taking the integer part of a real number i.e. the floor() function from JavaScript. We have an 'absolute' block. a 'floor' block would sit nicely alongside it. There are probably other basic simple JavaScript functions which would make useful blocks bit 'floor' is the one I need now.

Cheers

**Comment by pelikhan** [comment] 2016-08-18 00:22
No floating points on the micro:bit.

**Comment by thomasdenney** [comment] 2016-09-06 10:00
Duplicate of https://github.com/Microsoft/pxt-microbit/issues/205

**Closed by thomasdenney** 2016-09-06 10:00 UTC
Labels: bug, docs
