### ISSUE TITLE
Video in About Bluetooth page is broken

### ISSUE THREAD

**Issue by bluetooth-mdw** [Microsoft/pxt-microbit#154] opened 2016-06-29 13:28 UTC
![image](https://cloud.githubusercontent.com/assets/8341666/16453690/b164db56-3e05-11e6-963d-04ab234c6087.png)

**Comment by thomasdenney** [comment] 2016-07-12 08:45
It looks like this is fixed now. Are there any steps to reproduce? It works fine for me in Edge and Chrome.

**Comment by gingemonster** [comment] 2016-07-21 19:35
looks fine here as well

**Comment by pelikhan** [comment] 2016-08-01 20:20
Fixed.

**Closed by pelikhan** 2016-08-01 20:20 UTC
Labels: bug
