### ISSUE TITLE
Less memory available in beta?

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#2178] opened 2019-06-11 20:06 UTC
**Describe the bug**
This program causes panic 020 after 16 iterations when compiled on beta but lasts for 32 iteration on live.
https://makecode.microbit.org/_gr4LJPaL3gva

**To Reproduce**
1. Go to 'https://makecode.microbit.org/_gr4LJPaL3gva'
2. Click on 'Edit'
3. Download to micro:bit
4. Click Show Console Device
5. See panic 020 after 32 iterations
6. Change to beta, Download, Show Console Device
7. See panic 020 after 16 iterations

**Expected behavior**
Beta and live should be similar.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version
makecode.microbit.org version:  1.4.16
Microsoft MakeCode version:  5.15.6
microbit runtime version:  pxtgc-0

**Comment by abchatra** [comment] 2019-06-11 23:36
Dupe of #2177 Both have infinitely increasing arrays.

**Closed by abchatra** 2019-06-11 23:36 UTC

**Comment by martinwork** [comment] 2019-06-12 10:20
Not a duplicate. The panic is different. The array only increases 16 times. The point is about less memory being available. So before I could add 32 items, now only 16.
