### ISSUE TITLE
Serial mode: provide time information in chart cursor call out box 

### ISSUE THREAD

**Issue by microbit-josephine** [microsoft/pxt-microbit#4328] opened 2021-08-11 08:03 UTC
**Describe the solution you'd like**
In Serial mode, provide time information in chart cursor call out box. 

The box should display the time at which the data is seen:

<img width="312" alt="Screenshot 2021-08-16 at 09 15 04" src="https://user-images.githubusercontent.com/54458430/129525389-c34cfbd0-ef87-4b1f-903f-9140324ec861.png">
**Additional context**
This request was raised in a micro:bit support ticket https://support.microbit.org/a/tickets/47025

**Comment by abchatra** [comment] 2021-08-11 16:38
Duplicate of https://github.com/microsoft/pxt-microbit/issues/4329?

**Comment by microbit-josephine** [comment] 2021-08-16 07:14
Subtle difference, as this request was for time to be shown in the call out box, as opposed to time being displayed on the axis of the serial data logger. However, I could merge them into one ticket if you'd like?

**Comment by abchatra** [comment] 2021-08-16 20:02
Merging seems good. Please just add these details in the #4329

**Closed by abchatra** 2021-08-16 20:02 UTC
Labels: enhancement, serial
