### ISSUE TITLE
Simulator crashed, no error handler TypeError: pxsim.serial.readBuffer is not a function

### ISSUE THREAD

**Issue by liam2014** [Microsoft/pxt-microbit#919] opened 2018-07-04 10:51 UTC
hi, I want to use: 

let onBuffer: Buffer = serial.readBuffer(64);

but it make a  error:

Simulator crashed, no error handler TypeError: pxsim.serial.readBuffer is not a function

error screenshots  image:
[http://f.robobloq.com/img/error/error2.jpg](https://f.robobloq.com/img/error/error2.jpg)

I look up from official sources and test by official example. Still can't solve it.

help me,thanks !

**Comment by abchatra** [comment] 2018-07-06 17:17
Duplicate of https://github.com/Microsoft/pxt-microbit/issues/861

**Closed by abchatra** 2018-07-06 17:17 UTC
