### ISSUE TITLE
Recommend "Take Tour" over "Tour" in help menu if it will fit

### ISSUE THREAD

**Issue by kiki-lee** [microsoft/pxt-microbit#5010] opened 2023-03-24 17:10 UTC
"Tour" doesn't instinctively click in the mind as to what it could be. "Take Tour" is more active and helps get the idea across of what they're signing up for. 

![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/1633958/227594235-d909e39c-ee2d-4ec0-8280-11a69d9813e5.png)

**Comment by thsparks** [comment] 2023-03-24 17:33
I would recommend "Editor Tour" which feels a little more natural to me. Or perhaps "Tour Editor" if you want it to be an action.

**Comment by thsparks** [comment] 2023-03-24 21:11
I think the issue is "tour" by itself is confusing. I wouldn't know what that meant without more context. Maybe we can think of a more descriptive single word? But I don't have any off the top of my head.

**Comment by abchatra** [comment] 2023-03-24 21:44
I am fine if we have a better short word without being fully descriptive. @kimprice didn't the user study say, kids knew what tour meant?

**Comment by kimprice** [comment] 2023-03-24 21:57
Yes, all three knew what "tour" meant.

**Comment by abchatra** [comment] 2023-03-24 22:07
Won't fix.

**Closed by abchatra** 2023-03-24 22:07 UTC
Labels: enhancement, tour
