### ISSUE TITLE
version spec mismatch on midi error when importing file with midi blocks

### ISSUE THREAD

**Issue by machinehistories** [microsoft/pxt-microbit#1256] opened 2018-09-17 03:59 UTC
This file was originally made 11 months ago. It looks like previous files with midi bluetooth are not loading in either the beta or current editor. May I ask what is the best way to update files made in previous versions of makecode. Also is there a way to review the java code used in the hex file. 
[microbit-midi_serial.uploaded.zip](https://github.com/Microsoft/pxt-microbit/files/2387331/microbit-midi_serial.uploaded.zip)

**Comment by pelikhan** [comment] 2018-09-17 04:04
@riknoll looks like a good test case for your upgrading logic

**Comment by riknoll** [comment] 2018-09-17 17:26
It's a capitalization error in the dependencies. Does Github care about capitalization in repo or organization names? If not, we should normalize them

**Comment by pelikhan** [comment] 2018-09-17 17:27
GitHub does (should) not care but we might

**Comment by riknoll** [comment] 2018-09-17 17:28
@mmoskal do you see any problem with us converting all repo and organization names to lowercase? I assume it will invalidate the current caches but should be fine after that?

**Comment by riknoll** [comment] 2018-09-17 17:29
For reference, here is the `pxt.json`:

```json
{
    "name": "midi_serial",
    "dependencies": {
        "core": "*",
        "bluetooth": "*",
        "midi": "github:microsoft/pxt-midi#v2.0.3",
        "bluetooth-midi": "github:microsoft/pxt-bluetooth-midi#v2.0.3",
        "filesystem": "github:microsoft/pxt-filesystem#v0.9.2",
        "devices": "*"
    },
    "description": "",
    "files": [
        "main.blocks",
        "main.ts",
        "README.md"
    ]
}
```


Microsoft should be capitalized

**Comment by mmoskal** [comment] 2018-09-17 18:11
I think we should go for converting to all-lowercase

**Comment by machinehistories** [comment] 2018-09-18 05:03
I can now successfully open files with bluetooth midi iblocks while using
the makecode beta so thanks very much. Unfortunately upon uploading the
code the board isn't being recognized as bluetooth midi device. However, if
I take the exact same code and try it on the non beta site and upload it
onto a board running the previous firmware it works just fine and is
properly recognized as a midi device. I am using windows 10 and midiberry
to access the bluetooth midi stream. thanks, jason

**Comment by machinehistories** [comment] 2018-09-22 08:29
I am finding that whenever I attempt to use bluetooth midi with the beta release it hangs on upload or it will give me a "compilation failed please check code for errors however there aren't any errors shown."

**Comment by abchatra** [comment] 2020-03-20 16:56
Closing more than an year old bugs. If this still reproduces please reopen.

**Closed by abchatra** 2020-03-20 16:56 UTC
Labels: P2, bug
