### ISSUE TITLE
Incorrect highlight on tutorial Name Tag

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#2759] opened 2020-04-02 03:37 UTC
**Describe the bug**
Incorrect highlight on tutorial **Name Tag**

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Tutorials-->Name Tag->Python Start Tutorial
3.Click step 3 & 5

**Expect behavior**
The highlighted position is consistent with the description

**Actual behavior**
The highlighted position is inconsistent with the description.
We should highlight **show string** on step 3
![image](https://user-images.githubusercontent.com/59192069/78208064-02fa4180-74d6-11ea-9393-d529d0470c6f.png)
We should highlight **show string** on step 5
![image](https://user-images.githubusercontent.com/59192069/78208126-2d4bff00-74d6-11ea-815c-6ebc454322cc.png)

Additional context
1.OS: Windows(rs6)
2.makecode.microbit.org version: 2.3.3
3.Microsoft MakeCode version: 5.37.6

**Comment by jwunderl** [comment] 2020-04-02 04:06
duplicate of https://github.com/microsoft/pxt-microbit/issues/2751

**Closed by jwunderl** 2020-04-02 04:06 UTC
