### ISSUE TITLE
[Keyboard Navigation - Make Code - Home page] Focus does not moves on 'POP UP' screen when pop screen is open on clicking on any option under ‘Home’ screen.

### ISSUE THREAD

**Issue by AtulAgrahari** [microsoft/pxt-microbit#2354] opened 2019-08-06 12:13 UTC
**User Experience:**
If focus order is not aligned with either the meaning or operation of the UI, it would be confusing for the Keyboard dependent users who navigate documents sequentially and expect the focus order to be consistent with the sequential reading order.

**Repro Steps:**
1. Launch application URL : https://makecode.microbit.org/beta 
2. Home page will open.
3. Navigate to the controls appearing under "Tutorials, Games and Radio Games" section in Home page.
4. Select any option and navigate to the details dialog box.
5. Verify the issue.

**Actual Result:**
Focus does not moves on 'POP UP' screen when pop screen is open on clicking on any option under ‘Home’ screen.
Focus is moving in background screen when 'details dialog box' pop up is open

**Expected Result:**
Focus should moves on 'POP UP' screen when pop screen is open on clicking on any option under ‘Home’ screen.

**Note:**
Same issue is also exists with Chrome.

**MAS Reference:**
MAS 2.4.3 - Focus Order (05)

Accessibility Insights! - Identify accessibility bugs before check-in and make bug fixing faster and easier.

[MAS2.4.3_Background focus.zip](https://github.com/microsoft/pxt-microbit/files/3472118/MAS2.4.3_Background.focus.zip)

**Comment by abchatra** [comment] 2019-08-06 15:31
Please re-test using beta site https://makecode.microbit.org/beta . If it reproduces let me know. I will reopen the bug.

**Comment by AtulAgrahari** [comment] 2019-08-08 07:40
Issue still exists in https://makecode.microbit.org/beta so reactivating the issue.

**Comment by jwunderl** [comment] 2019-08-08 20:43
this seems to be a duplicate of https://github.com/microsoft/pxt-microbit/issues/2355, correct? both seem to be saying that the issue is that it doesn't automatically focus on the start or collapse button

**Closed** 2019-08-13 22:56 UTC
Labels: accessibility

**Comment by sonimishra** [comment] 2019-08-30 11:47
Issue has been verified and now the  focus is navigating to the dialogue window.
Hence closing the bug.
