### ISSUE TITLE
The step number shows error

### ISSUE THREAD

**Issue by AimeeCao18** [Microsoft/pxt-microbit#1472] opened 2018-10-22 08:40 UTC
**Repro steps:**
1. Navigate to https://makecode.microbit.org/projects/milky-monster
2. Scroll down the scroll bar and click "Code"
3. Scroll down the scroll bar and observe the step number

**Expected result:**
The numerical order of the steps is correct

**Actual result:**
Step number shows error
![capture2](https://user-images.githubusercontent.com/44188776/47281795-4e38d100-d60f-11e8-9688-029b52a9b88d.PNG)

**Comment by abchatra** [comment] 2018-10-22 21:09
Duplicate of https://github.com/Microsoft/pxt-microbit/issues/1473

**Closed by abchatra** 2018-10-22 21:09 UTC
