### ISSUE TITLE
Memory corruption with infection on /beta

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt-microbit#1954] opened 2019-04-04 16:57 UTC
The infection game crashes on /beta. After pressing A+B, screen displays random images.

**Comment by abchatra** [comment] 2019-04-09 22:44
Assumption is typescript radio is going to fix this.

**Comment by riknoll** [comment] 2019-04-11 00:39
It did not fix it; still doesn't work with my changes in https://github.com/Microsoft/pxt-microbit/pull/2000

**Comment by riknoll** [comment] 2019-04-11 00:41
Duplicate of https://github.com/Microsoft/pxt-microbit/issues/1752

**Closed by riknoll** 2019-04-11 00:41 UTC
Labels: P1, bug, next-release
