### ISSUE TITLE
The Python class example does not compile

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#3456] opened 2020-10-21 16:47 UTC
**Describe the bug**
From: https://makecode.microbit.org/python/classes
```python
class Greeter:
    greeting = ""
    def __init__(self, message):
        self.greeting = message
    def greet(self):
        return "Hello, " + self.greeting

greeter = Greeter("world")
```

Throws the following errors:

```
Line 4: the field 'greeting' of 'Greeter' is static
Line 6: the field 'greeting' of 'Greeter' is static
```

**To Reproduce**
copy paste the code in the Python editor and see the error.

**Expected behavior**
Valid example that compiles correctly.

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 
![image](https://user-images.githubusercontent.com/29712657/96751629-55914180-13c5-11eb-92ca-a4be8a03a3cc.png)

**Desktop (please complete the following information):**
 - OS: macOs Mojave
 - Browser Chrome
 - Version 86

**Additional context**

**Comment by darzu** [comment] 2021-03-30 17:39
Duplicate of: https://github.com/microsoft/pxt-microbit/issues/3189

**Comment by darzu** [comment] 2021-03-30 17:40
Actually, slightly different symptoms. Will verify

**Comment by jaydeetay** [comment] 2021-06-18 02:28
I see this too. If you remove the static greeting member it doesn't help - the error just changes to "Type annotation cannot appear on a constructor declaration".
Github repo showing the issue: 
https://github.com/jaydeetay/pythontest2/blob/master/main.py

**Comment by jaydeetay** [comment] 2021-06-18 03:00
@microbit-mark

**Comment by microbit-mark** [comment] 2022-05-10 13:36
Also raised by user in https://support.microbit.org/a/tickets/53227 (private). Can we fix the issue/update the docs @abchatra?

**Closed** 2022-06-03 17:34 UTC
Labels: bug, P2, python, tsToPy
