### ISSUE TITLE
"SHAKE" button doesn't work when clicked once

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1981] opened 2019-04-08 06:13 UTC
**Describe the bug**
"SHAKE" button doesn't work when clicked once

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/beta#editor
2. Drag blocks as below shared project
https://makecode.microbit.org/_Hh5AVjfwjXcp
3. Click "SHAKE" to show a random number on simulator

**Expected behavior**
"SHAKE" button should work when clicked once

**Actual behavior**
"SHAKE" button doesn't work when clicked once
![Issue40801](https://user-images.githubusercontent.com/23466737/55701718-d157b300-5a06-11e9-83d9-25f4046dd334.gif)

**Additional info:**
- makecode.microbit.org version:  1.4.2
- Microsoft MakeCode version:  5.9.4
- This bug repro on each browser on Windows

**Comment by jwunderl** [comment] 2019-04-08 06:38
Duplicate of https://github.com/Microsoft/pxt-microbit/issues/1970 -- I thought it was specific to safari initially, but it does look like it is a regression across all browsers from the live site

**Comment by abchatra** [comment] 2019-04-08 16:10
Good find folks. I am closing this as a duplicate of #1970 and bumping it to P1

**Closed** 2019-04-08 16:14 UTC
