### ISSUE TITLE
Music Blocks change to"C" when changed to French

### ISSUE THREAD

**Issue by eric-camplin** [Microsoft/pxt-microbit#1585] opened 2018-11-04 18:12 UTC
**Describe the bug**
Change from English to French modifies note to be "C" for any different note

**To Reproduce**
youtu.be/mPUhwcriWCE  

1. view https://makecode.microbit.org/_0E3V7eJ2i7ye 
2. change language from English to French
3. open the link from history

**Expected behavior**
No change in Music tone

**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**Desktop (please complete the following information):**
 - OS: windows 10 
 - Browser chrome

**Comment by koichii** [comment] 2018-11-05 01:36
I would like to report the similarly problem.

**Describe the bug**
Edit v0 project in the new editor modifies note to be "C" for any different note

**To Reproduce**
Steps to reproduce the behavior:
1. oepn https://makecode.microbit.org/_LxsFW1exD34j
2. press Edit button

**Expected behavior**
No change in Music tone

**Comment by abchatra** [comment] 2018-11-05 17:06
This is dupe of https://github.com/Microsoft/pxt-microbit/issues/1570

**Closed by abchatra** 2018-11-05 17:06 UTC
