### ISSUE TITLE
windows offline app: unable to find installed app

### ISSUE THREAD

**Issue by eanders-ms** [microsoft/pxt-microbit#5249] opened 2023-06-16 17:18 UTC
After installing the microbit offline app for windows, the app is not discoverable from the start menu search. It is nowhere to be found.

App link: https://makecode.com/api/release/microbit/v6.0.5/win64

OS: Windows 11

**Comment by abchatra** [comment] 2023-06-16 17:37
Dupe of https://github.com/microsoft/pxt-microbit/issues/5197

**Closed by abchatra** 2023-06-16 17:37 UTC
