### ISSUE TITLE
Changing the tab while WebUSB is flashing causes errors

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#3677] opened 2020-11-12 15:56 UTC
**Describe the bug**
Changing the tab while WebUSB is flashing causes errors

**To Reproduce**
1. Go to MakeCode
2. Pair micro:bit
3. Click Download to WebUSB flash
4. Change tabs
5. MakeCode will trigger a hex file download to the PC and the flashing stops

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/29712657/98963144-3c307080-24ff-11eb-8e05-c732d2e7f010.png)
```
webusb: get devices
editor.js:2415 Connecting...
editor.js:2446 
pxtapp.js:1 Error: Disconnected
    at e.sendPacketAsync (https://pxt.azureedge.net/blob/90eb76d9d5fc5aa23f148af3b7a150ef720c3809/pxtapp.js:1:340824)
    at Object.writeAsync [as write] (https://pxt.azureedge.net/commit/23c3d8c7f8a0f44f7681d1e3de648cb6b67220d2/editor.js:3316:22)
    at CMSISDAP.<anonymous> (https://pxt.azureedge.net/commit/23c3d8c7f8a0f44f7681d1e3de648cb6b67220d2/editor.js:2522:55)
    at step (https://pxt.azureedge.net/commit/23c3d8c7f8a0f44f7681d1e3de648cb6b67220d2/editor.js:2317:23)
    at Object.next (https://pxt.azureedge.net/commit/23c3d8c7f8a0f44f7681d1e3de648cb6b67220d2/editor.js:2298:53)
    at https://pxt.azureedge.net/commit/23c3d8c7f8a0f44f7681d1e3de648cb6b67220d2/editor.js:2292:71
    at S.a._execute (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:980459)
    at S._resolveFromExecutor (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1010637)
From previous event:
    at S.L [as _captureStackTrace] (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:980993)
    at S._then (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1006494)
    at S.then (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1004857)
    at U.compile (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:60236)
    at e.compile (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:422988)
    at e.handleClick (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:431550)
    at Object.<anonymous> (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1437297)
    at _ (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1437335)
    at https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1437481
    at x (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1437567)
    at T (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1438012)
    at C (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1437824)
    at A (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1438172)
    at xn (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1465118)
    at le (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1551809)
    at Tn (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1465723)
    at On (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1466680)
    at An (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1465968)
    at s.unstable_runWithPriority (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1556600)
    at Wi (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1481559)
    at ae (https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1550422)
    at https://pxt.azureedge.net/blob/cbe3b5d02175220060a0693d1ff35ab514db89ba/main.js:1:1465257
```

**micro:bit version (please complete the following information):**

V2

**Desktop (please complete the following information):**
OS: macOS
Browser Chrome
Version 86.0.4240.183

**Additional context**

https://makecode.microbit.org/beta
makecode.microbit.org version:  3.0.17
Microsoft MakeCode version:  6.0.18
microbit runtime version:  v2.2.0-rc6

**Comment by abchatra** [comment] 2020-11-12 17:34
Not a blocking bug at this point of time.

**Comment by pelikhan** [comment] 2021-03-25 08:46
Changing tab will disconnect the device, which in the middle of a download will fail the download.

**Comment by pelikhan** [comment] 2021-03-25 08:47
@abchatra This is working as designed unless you want to change the tab behavior.

**Comment by pelikhan** [comment] 2021-03-25 08:47
Similar to https://github.com/microsoft/pxt-microbit/issues/3706

**Comment by abchatra** [comment] 2021-03-29 16:39
This is duplicate of https://github.com/microsoft/pxt-microbit/issues/3706

**Closed by abchatra** 2021-03-29 16:39 UTC
Labels: P2, bug, webusb
