### ISSUE TITLE
makecode extensions translation bug

### ISSUE THREAD

**Issue by smfox10** [microsoft/pxt-microbit#4280] opened 2021-07-21 11:43 UTC
Hello everyone, this is CCFIVE from Kittenbot
We noticed that the Makecode platform has been updated recently. Thank you for your efforts. Teachers have always liked this platform.

Recently, many teachers have reported to us that when they load some extensions and refresh the page, the translations of the extensions are all invalid, and all translations from Chinese are translated into English. Before the platform is updated, the extensions can be displayed normally

Steps to reproduce the bug:
1. Open the online programming webpage,  set the language display to Chinese
![image](https://user-images.githubusercontent.com/3880290/126483113-075acb53-6cd8-4805-9deb-5b727d665d50.png)

2. Load Robotbit extensions (or maqueen)
![image](https://user-images.githubusercontent.com/3880290/126483167-dcabe6cb-8646-43a5-92fd-5b5dd21691a9.png)

3. The plug-in loaded at this time is displayed in Chinese

4. Refresh this page, translations changed to English
![image](https://user-images.githubusercontent.com/3880290/126483248-0ac259c2-5943-4cc2-9877-df25615a42fe.png)

**Comment by microbit-mark** [comment] 2021-07-21 14:43
This issue looks like a duplicate of https://github.com/microsoft/pxt-microbit/issues/4274 which should be fixed in an upcoming release.

**Comment by abchatra** [comment] 2021-07-22 21:46
@riknoll can you verify this is indeed fixed?

**Comment by lioujj** [comment] 2021-07-23 03:59
This situation is a bit disturbing.

**Comment by abchatra** [comment] 2021-07-23 04:48
@lioujj we are going to release soon with the bug fix. Thanks for patience

**Comment by riknoll** [comment] 2021-07-26 17:49
Fixed in makecode.microbit.org/stable

**Comment by abchatra** [comment] 2021-07-30 23:38
Fixed and point fix released.

**Closed by abchatra** 2021-07-30 23:38 UTC
Labels: P2, bug, localization, next-release
