### ISSUE TITLE
Play Sound in Background inside a Forever loop will keep looping the sound even when the simulator is stopped or the block is deleted

### ISSUE THREAD

**Issue by kiki-lee** [microsoft/pxt-microbit#4751] opened 2022-06-14 04:09 UTC
**Describe the bug**
Was playing with the new sound effects block trying to figure out what "in background" does and put it inside a forever loop.  The sound kept playing, even after I stopped the simulator.  Even after I deleted the block altogether and deleted all blocks inside the workspace.  Had to refresh the browser to get it to stop.

**To Reproduce**
![image](https://user-images.githubusercontent.com/1633958/173491383-227e61d5-9c8b-47e0-b647-cac4b331c7a6.png)

**Expected behavior**
I expected the sound to play in the "forever" that was limited to that one instance of the program running.

**Comment by abchatra** [comment] 2022-06-14 04:41
Duplicate of https://github.com/microsoft/pxt-microbit/issues/4736

Thanks @kiki-lee 

FYI @riknoll

**Closed by abchatra** 2022-06-14 04:41 UTC
