### ISSUE TITLE
Accept Arrays for the Function blocks

### ISSUE THREAD

**Issue by fengrun85** [microsoft/pxt-microbit#3323] opened 2020-07-19 18:06 UTC
Currently custom Functions block do not accept Arrays.

Would be good if it can accept array of values.

**Comment by abchatra** [comment] 2020-07-20 20:16
Note: All variables in the blocks are global.

**Comment by abchatra** [comment] 2021-03-23 07:09
Duplicate of https://github.com/microsoft/pxt-microbit/issues/2205

**Closed by abchatra** 2021-03-23 07:09 UTC
Labels: apis, enhancement, functions
