### ISSUE TITLE
Entering into a project resets a microbit connected over webusb

### ISSUE THREAD

**Issue by riknoll** [microsoft/pxt-microbit#3710] opened 2020-11-13 18:37 UTC
To reproduce:
1. Flash a program to the micro:bit where you will be able to tell if it resets. I used [ghost of john](https://makecode.microbit.org/_1Hv4csC87Pjv) (copied from [this forum post](https://forum.makecode.com/t/ghost-of-john/4363))
2. Go to the home screen
3. Open a project
4. Notice that the connected micro:bit resets

Tested on macOS on Chrome with a micro:bit that had been connected over webusb

**Comment by pelikhan** [comment] 2020-11-16 07:45
This is by design. When we connet via WebUSB, we configure DAPLink the serial baudrate; which has a side-effect of reseting the board. Probably worth adding to an FAQ since this is not the first time it is reported.

**Comment by AlasdairAtKitronik** [comment] 2020-12-04 10:15
> This is by design. When we connet via WebUSB, we configure DAPLink the serial baudrate; which has a side-effect of reseting the board. Probably worth adding to an FAQ since this is not the first time it is reported.

@pelikhan @abchatra Is there any way of getting round this? 
I also found this issue when I had spent a week logging data on the micro:bit, connected it to MakeCode via WebUSB to transfer over the serial interface, the micro:bit reset and I lost all my data. 

Data logging is something schools really want to do, but it's not practical to keep micro:bits constantly plugged into a computer, especially as they probably want to measure something that isn't stationary, or isn't in a computer lab.

**Comment by AlasdairAtKitronik** [comment] 2020-12-04 10:33
Using a terminal program like Tera Term and setting up the connection, changing the baud rate etc doesn't reset the micro:bit, and still allows all the data to be transferred, so why does the same thing with WebUSB in MakeCode cause a reset?

**Comment by pelikhan** [comment] 2020-12-08 06:25
DAPLink resets the NRf when we set the baud rate.

________________________________

**Comment by pelikhan** [comment] 2021-03-25 08:40
Won't fix or needs to be ported upstream to DapLink.

**Comment by abchatra** [comment] 2021-03-29 16:36
This is by design. This needs a upstream to Microbit foundation. Please raise with foundation if these needs to be fixed.

**Closed by abchatra** 2021-03-29 16:36 UTC
Labels: P2, bug, webusb
