### ISSUE TITLE
Exiting tutorial loses user's code

### ISSUE THREAD

**Issue by darzu** [Microsoft/pxt-microbit#1898] opened 2019-03-02 20:53 UTC
**Describe the bug**
When exiting a tutorial, the user is brought back to the home screen instead of a new project with the tutorial blocks they placed.

**To Reproduce**
1. microbit.makecode.com/beta
2. click "flashing heart" tutorial
3. place some blocks
4. click the "exit tutorial" button
5. notice you're on the home screen

**Expected behavior**
the tutorial blocks should have stayed as part of a new project.

**Screenshots**
![leave-tut-safari](https://user-images.githubusercontent.com/6453828/53687502-155de680-3cea-11e9-88f0-2e8e3deb61d9.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3 (18D109)
 - Browser Safari Version 12.0.3 (14606.4.5)
 - Browser Chrome 72
 - MacBook Pro 2018, i9, 32GB

**Comment by darzu** [comment] 2019-03-05 15:59
Repros on Chrome as well

**Comment by abchatra** [comment] 2019-03-06 05:53
I believe this is per design. If you are exiting the tutorial, likely you are going to want to try another tutorial. Compared to finishing tutorial we drop in the editor, so you can start something else.

**Comment by darzu** [comment] 2019-03-08 02:23
So there's no way to get rid of the "tutorial mode" while still keeping whatever code you've written? It seems like we'd want a way for users that go "off rail" to be able to keep whatever they've built. Imagine a user gets inspired during with a project during the middle of a tutorial and builds a big program that's not what the tutorial wants. They should be able to keep that somehow.

I feel like we should default to an option that doesn't lose a user's work. Also, it looks like in tutorial mode the "save" button and name field are gone.

Also, one of the bullet points from the release testing plan is this:

> Make sure you can exit the tutorial and keep your current code (it will be in a new project)

which is why I filed this issue in the first place.

**Comment by abchatra** [comment] 2019-03-08 02:48
If you finish the tutorial, your code will be kept and you will be in the editor.

**Comment by abchatra** [comment] 2019-03-08 02:48
Only exit tutorial gets you back to home screen.

**Comment by darzu** [comment] 2019-03-08 19:57
> If you finish the tutorial, your code will be kept and you will be in the editor.

Right, but I think would should be friendly to users who go off the rails. If someone is on step 3 of 10 and decide they don't want to finish the tutorial but want to keep their code, they need a way to do so IMO.

**Comment by abchatra** [comment] 2019-03-15 06:41
Intent might be try another tutorial. It is hard to argue either way. Also code saved as a project in the project list.

I am inclined to close this as by design.

**Comment by darzu** [comment] 2019-03-15 10:11
> Also code saved as a project in the project list.

Ah I didn't notice this. That's good enough IMO

**Comment by abchatra** [comment] 2019-03-15 23:40
by desgin

**Closed by abchatra** 2019-03-15 23:40 UTC
