### ISSUE TITLE
Radio.writeValueToSerial() not working with radio.sendString()

### ISSUE THREAD

**Issue by gbaman** [Microsoft/pxt-microbit#74] opened 2016-05-25 01:46 UTC
When using ```radio.sendString("Hello")``` with ```radio.writeValueToSerial()```, all I get onto the serial console is a blank JSON reply - ```{}```.
```radio.sendValue()``` and ```radio.sendNumber()``` work as expected with ```radio.writeValueToSerial()```.

Test program I am using is:
```Typescript
input.onButtonPressed(Button.A, () => {
    radio.sendString("ABC");
});
input.onButtonPressed(Button.B, () => {
    radio.sendValue("Hello", 2);
});
input.onGesture(Gesture.Shake, () => {
    radio.sendNumber(42);
});
radio.onDataReceived(() => {
    radio.writeValueToSerial();
});


```

**Comment by abchatra** [comment] 2016-10-15 01:09
@riknoll Please take look if this will be fixed by your callback work on radio. If yes close this issue and tag it with the issue in pxt.

**Comment by riknoll** [comment] 2016-10-15 01:25
Nope, this is an unrelated issue. I'm not sure this is actually a bug, but more an issue caused by our confusing APIs. Here are what the packets we send look like:

API                         | 1         | 2     | 3                             | 4             | 5
----------------------------|-----------|-------|-------------------------------|---------------|-------
`sendNumber(value)`         | value     | time  | serial number (*optional*)    |               |
`sendValue(value, name)`    | value     | time  | serial number (*optional*)    | name length   | name...
`sendString(string)`        | string...    |       |                               |               | 

As you can see, the packets we send don't contain any data saying what the payload actually contains. All of our APIs just assume a packet structure because we have no way of verifying the actual contents. `writeValueToSerial()` assumes that the packet that was received is of the first or second type above. If you send it a string packet, it will try and read that as a key-value pair and fail miserably. Same goes with sending a number and calling `receiveString()`, etc.

The only real way for us to fix it would be to redo the packets we send to include a byte that says what they contain. That would probably be a big breaking change, though.

**Comment by abchatra** [comment] 2016-10-15 01:34
Thanks @riknoll! Got it. If you send string, then you will have to receive the using radio.receiveString().  Closing

**Comment by pelikhan** [comment] 2016-10-15 01:36
The internal layout of packets is not documented, so we can add a byte to specify the packet type / layout.

**Comment by riknoll** [comment] 2016-10-15 01:40
Sure, I'll move this to PXT and assign it to me.

**Closed** 2016-10-15 01:44 UTC
Labels: apis, bug
