### ISSUE TITLE
Beta: Can't change language by clicking a language name in the Language dialogue

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#5119] opened 2023-05-08 20:02 UTC
**Describe the bug**

Can't change language by clicking a language name in the Language dialogue.

**To Reproduce**
1. Go to https://makecode.microbit.org/beta#editor
2. Click on 'More...' then 'Language'
3. Click a language name

**Expected behavior**
Can change language.

**micro:bit version (please complete the following information):**
not hardware related

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  Windows 10
 - Browser [e.g. chrome, safari] Chrome, Edge
 - Version [e.g. 22] 112.0.5615.139, 113.0.1774.35

**Comment by abchatra** [comment] 2023-05-09 16:44
@eanders-ms dupe of https://github.com/microsoft/pxt-microbit/issues/5079?

**Comment by abchatra** [comment] 2023-05-09 16:45
@martinwork only when signed in?

**Comment by jwunderl** [comment] 2023-05-09 16:48
This looks fixed in v5.1.26, we just hadn't bumped since the fix was pushed in (and coincidentally bumped within minutes of this issue being filed)

**Closed by jwunderl** 2023-05-09 16:48 UTC
Labels: bug, P2

**Comment by martinwork** [comment] 2023-05-09 19:06
Thanks @abchatra @jwunderl . I can change the language now whether or not signed in.
