### ISSUE TITLE
A variable cannot be set to a string using blocks

### ISSUE THREAD

**Issue by rharbird** [Microsoft/pxt-microbit#95] opened 2016-06-10 14:17 UTC
AFAICS, there is no way to set a variable to a string or boolean value.

It is possible to set a variable to the output of a function which has a return type of string. I can use blocks to generate this code:

let item: string = "";
while (true) {
    item = serial.readLine();
    basic.pause(100);
}

**Comment by cpseager** [comment] 2016-06-10 14:49
I think you'll find the issue is simply that the 'string' block is accidentally missing from the toolbox - this looks like a bug to me. You should be able to assign a string to a variable, but can't do that if you can never pull out a string block to start with!

This omission also means that you can't ever change a string 'shadow' block into a 'real' block.

**Comment by rharbird** [comment] 2016-06-10 15:17
Yes, I'm hoping that means it will be pretty straightforward to fix with a couple of new blocks.

**Comment by cpseager** [comment] 2016-06-10 15:30
BTW Boolean is already there (in logic section) it's only string that is missing.

![image](https://cloud.githubusercontent.com/assets/7423187/15969558/850f66de-2f28-11e6-858d-5793e75d6725.png)

**Comment by tballmsft** [comment] 2016-06-14 14:58
We are working to get parity between blocks and typescript.

**Comment by abchatra** [comment] 2016-10-15 01:23
This is duplicate of #72 . Closing this as #72 has detailed description

**Closed by abchatra** 2016-10-15 01:23 UTC
Labels: bug
