### ISSUE TITLE
Arrays as function parameters in block view

### ISSUE THREAD

**Issue by kristianpedersen** [microsoft/pxt-microbit#3447] opened 2020-10-16 15:02 UTC
I wish I could show arrays being used as function parameters in block view.

```typescript
function a (n: number) {
    basic.showNumber(n ** n)
}

function b(n: number[]) {
    for (const val of n) {
        basic.showNumber(val ** val)
    }
}
a(3)
b([4, 5, 6])
```

gets converted to this:

![microbit-screenshot (4)](https://user-images.githubusercontent.com/5204369/96274785-38c5ca00-0fd1-11eb-977a-03e502e12fb6.png)

**Comment by n3wsw3** [comment] 2020-10-21 14:11
An addition to this is to make it so functions with custom classes as parameters also get converted.
Right now it looks like LedSprite and Game is added to the available function parameter types in pxtarget.json (runtime.functionsOptions.extraFunctionEditorTypes).
One way to do this would be to add a setting above an exported class (Similar to the color and icon)
```js
//% function_parameter 
export class CustomType {
    ...
}
```
And make all of the classes marked with function_parameter available in the editor as function parameters

**Comment by abchatra** [comment] 2021-03-23 07:09
Duplicate of https://github.com/microsoft/pxt-microbit/issues/2205

**Closed by abchatra** 2021-03-23 07:09 UTC
Labels: enhancement, functions
