### ISSUE TITLE
Project thumbnail not generating in share dialog

### ISSUE THREAD

**Issue by eanders-ms** [microsoft/pxt-microbit#5036] opened 2023-03-31 17:36 UTC
After completing the Flashing Hearts tutorial, I clicked the share button. In the share dialog, the project thumbnail box displays a progress spinner that doesn't resolve.

![image](https://user-images.githubusercontent.com/12176807/229190643-6c9cdb35-c953-4ced-b29c-35beebb8f1ad.png)

Manually updating the project thumbnail works as expected.

**Comment by abchatra** [comment] 2023-03-31 17:44
Duplicate of https://github.com/microsoft/pxt-microbit/issues/4987

**Closed by abchatra** 2023-03-31 17:44 UTC
