### ISSUE TITLE
Kitronik :KLEF Piano does not work with micro:bit V2

### ISSUE THREAD

**Issue by AlasdairAtKitronik** [microsoft/pxt-microbit#3531] opened 2020-10-30 10:09 UTC
**Describe the bug**
The Kitronik :KLEF Piano does not work when using a micro:bit V2 (see extension: https://github.com/KitronikLtd/pxt-kitronik-klef-piano). The Piano uses a capacitive touch sensor, communicating with the micro:bit via I2C. With V2, key presses are either not registered at all, or are delayed by about 10 seconds, and then register all together. 

**To Reproduce**
1. Go to MakeCode beta editor and create a new project.
2. Add the Kitronik Klef Piano extension.
3. Create this simple program to setup the piano and allow it to be played:
![image](https://user-images.githubusercontent.com/36475405/97692109-41b99f80-1a97-11eb-99e8-992c49feffd2.png)
4. Download the program to a V2 micro:bit and see that it does not play as expected (i.e. when you press the key, a tone will not be played from the speaker).

**Expected behavior**
This same program created in the MakeCode beta editor was downloaded to a V1.5 micro:bit and the piano behaved as expected, with tones playing through the speaker when keys were pressed.

**micro:bit version:**
Broken on micro:bit V2, works on micro:bit V1.5.

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 86.0.4240.111 (Official Build) (64-bit)

**Comment by abchatra** [comment] 2020-11-03 16:18
@microbit-carlos @jaustin

**Comment by microbit-carlos** [comment] 2020-11-03 16:23
@AlasdairAtKitronik for the I2C write-read commands (or any I2C successive commands/transfers), could you try using repeated starts and see if that works? Right now all of them set that argument to `false`.

**Comment by AlasdairAtKitronik** [comment] 2020-11-05 10:19
@microbit-carlos I have tried various different ways of doing the I2C writes: set them to true, multi-byte block writes - nothing is working for the V2 micro:bit.

**Comment by microbit-carlos** [comment] 2020-11-05 10:45
Are you able to read the chip ID only from register 0x0 correctly? It'd be good to test that with and without the repeated start.
An isolated simple read function in a normal MakeCode programme without any extension would be best.

If that MakeCode test works for v1 and not for v2, would you be able to check if the same doesn't work in a C++ CODAL programme? This could be used a base:

```cpp
#include "MicroBit.h"

MicroBit uBit;

static const uint16_t ADDR = 0x0D << 1;

int chipId() {
    int result;

    uint8_t reg = 0x01;
    result = uBit.i2c.write(ADDR, &reg, 1, true);
    if (result != MICROBIT_OK) {
        uBit.display.print(result);
        return -1;
    }

    uint8_t buffer[1] = {0xFF};
    result = uBit.i2c.read(ADDR, buffer, 1);
    if (result != MICROBIT_OK) {
        uBit.display.print(result);
        return -2;
    }
    return buffer[0];
}

int main() {
    int id = chipId();

    while(1) {
        uBit.display.print(id);
        uBit.sleep(1000);
        uBit.display.clear();
        uBit.sleep(1000);
    }
}
```

**Comment by AlasdairAtKitronik** [comment] 2020-11-06 10:44
> Are you able to read the chip ID only from register 0x0 correctly? It'd be good to test that with and without the repeated start.
> An isolated simple read function in a normal MakeCode programme without any extension would be best.

I have successfully managed to read the chip ID correctly on V1 and V2 with the following simple program in MakeCode:
```typescript
const CHIP_ADDRESS = 0x0D;
let buff = pins.createBuffer(1);
input.onButtonPressed(Button.A, function () {
    pins.setPull(DigitalPin.P1, PinPullMode.PullUp)
    if (pins.digitalReadPin(DigitalPin.P1) == 0) {
        buff[0] = 0
        pins.i2cWriteBuffer(CHIP_ADDRESS, buff, false)
        buff = pins.i2cReadBuffer(CHIP_ADDRESS, 1, false)
        while (buff[0] != 0x11) {
            buff = pins.i2cReadBuffer(CHIP_ADDRESS, 1, false)
        }
        basic.showNumber(buff[0])
    }
})
```
It also works if I set the initial i2cWriteBuffer to be repeating start, but not if I set the others to 'true' as well.

**Comment by microbit-carlos** [comment] 2020-11-06 10:52
> It also works if I set the initial i2cWriteBuffer to be repeating start, but not if I set the others to 'true' as well.

Right, a repeated start is common in-between write-read operations. For other operations I would not enable it.

Does changing setting the repeat start in those situations fix the current issues with the accessory?

**Comment by AlasdairAtKitronik** [comment] 2020-11-06 11:32
It now makes it through the setup procedure, and some of the key presses are registering, but it still isn't working with V2 in the same way it does with V1 micro:bit. Lot's of the key presses are missed, some of the ones that are registered then stay 'on' much longer than they should, and there's a constant loud background hiss and whine coming out of the Piano Speaker, which isn't present with a V1.

**Comment by microbit-carlos** [comment] 2020-11-06 11:56
> there's a constant loud background hiss and whine coming out of the Piano Speaker, which isn't present with a V1.

Is there any noise present before any audio is played?

> Lot's of the key presses are missed, some of the ones that are registered then stay 'on' much longer than they should

If all the sound-making stuff is replaced by something like sending serial data or putting something on the display (serial is probably easier to track), does it still lose presses?

**Comment by AlasdairAtKitronik** [comment] 2020-11-06 11:56
With some more changes to having repeated starts elsewhere, the piano is now playing correctly with correctly registered key presses - thank you @microbit-carlos .
However, there is still this constant background whine and hiss from the Piano speaker. I have disabled the onboard speaker for V2, but this has had no impact. The piano speaker is also in P0.

**Comment by jaustin** [comment] 2020-11-06 12:00
Another way to take the software mixer out of the... mix... would be to call pins.setAnalogPitchPin to choose the speaker pin explicitly

https://makecode.microbit.org/v1/reference/pins/analog-set-pitch-pin

**Health warning** this will disconnect the internal mixer from the pin and you will only get sounds from the melody blocks NOT sounds from the 'play sound' block (these rely on the synthesizer and mixer to work).

But it'd still be useful to know if that hiss is from the mixer

**Comment by AlasdairAtKitronik** [comment] 2020-11-06 12:01
Thanks @jaustin, I'll try that now.

**Comment by AlasdairAtKitronik** [comment] 2020-11-06 12:05
> Another way to take the software mixer out of the... mix... would be to call pins.setAnalogPitchPin to choose the speaker pin explicitly

That's completely got rid of the background speaker noise, thank you @jaustin.
Shame we can't use the new synthesised sounds.

**Comment by jaustin** [comment] 2020-11-06 12:12
Okay, so I think that needs a bit more explanation, as I think it's a workaround not a solution :)

<img width="985" alt="image" src="https://user-images.githubusercontent.com/147113/98364686-274c6c80-2029-11eb-8e11-fbfcacee734c.png">
<img width="984" alt="image" src="https://user-images.githubusercontent.com/147113/98364720-33d0c500-2029-11eb-96e8-6ac040918d48.png">

I've highlighted in red the things I'm concerned about for users in this case. It is fully V1 compatible, but that isn't necessarily what people might expect! Tricky to work out the right thing to do here :)

These are some quick modification of @finneyj's slides and in general, we should fix the fact we have some noise entering somewhere from the mixer pipeline.

**Comment by AlasdairAtKitronik** [comment] 2020-11-06 12:15
Right, thanks for the slides - helpful to see what the process is. 
Is there more testing of stuff I can do, or is it some back end stuff which might need changing?

**Comment by jaustin** [comment] 2020-11-06 13:47
I think one useful thing you could do is see what action starts the hiss - on power on I expect it to be silent. Play a sound (like "happy"), does that start the hiss? What if you play a note from 'melody' first? Something like this 
```typescript
input.onButtonPressed(Button.A, function () {
    music.playTone(262, music.beat(BeatFraction.Whole))
})
input.onButtonPressed(Button.B, function () {
    soundExpression.giggle.playUntilDone()
})
input.onLogoEvent(TouchButtonEvent.Pressed, function () {
    music.setOnBoardSpeakerEnabled(false)
})
```

**Comment by finneyj** [comment] 2020-11-06 13:52
yes - that would be really useful. We haven't encountered any hiss anywhere else yet...

**Comment by AlasdairAtKitronik** [comment] 2020-11-06 14:55
Tried this test program:
```typescript
input.onButtonPressed(Button.A, function () {
    music.playTone(262, music.beat(BeatFraction.Double))
})
input.onButtonPressed(Button.AB, function () {
    music.startMelody(music.builtInMelody(Melodies.Prelude), MelodyOptions.Once)
})
input.onButtonPressed(Button.B, function () {
    soundExpression.happy.play()
})
``` 
(**Note**: I tried this with the onboard speaker both enabled, and disabled - it made no difference to the end result).

There was no hiss/whine at power up, but doing any action - whether melody, single note, or new sounds - then led to the hiss noise starting.

This video demonstrates the audio issue:
[Kitronik_Piano_V2_issue_Trim.zip](https://github.com/microsoft/pxt-microbit/files/5501852/Kitronik_Piano_V2_issue_Trim.zip)

**Comment by finneyj** [comment] 2020-11-06 18:00
Thanks @AlasdairAtKitronik.

If you run the same code and pop in some headphones attached to P0, can you still hear the same noise? It would be good to rule out something on your board somehow picking up a subharmonic?

**Comment by AlasdairAtKitronik** [comment] 2020-11-10 09:32
@finneyj 
I have tried the headphone thing today, but didn't get anywhere as there appears to be a more fundamental issue:
I can't get any sound at all from a V2 micro:bit programmed in beta.

I tried the same program as before, and tried playing the sounds through the onboard buzzer, through the Piano speaker, and through headphones - no sound at all. I tried a similar program on V1 micro:bit, again programmed from beta, and the audio out was exactly as expected on the headphones.

Have changes been made to the backend audio stuff?

**Comment by jaustin** [comment] 2020-11-10 12:04
Can you please share the hex @AlasdairAtKitronik ? If we just connect headphones and nothing else will we hear the hiss?

**Comment by AlasdairAtKitronik** [comment] 2020-11-10 12:22
@jaustin Really, just realised the error in my last comment:

With the headphones, there is **no** hiss/whine - I can only get it to happen with the speaker on the Piano.

**Comment by finneyj** [comment] 2020-11-10 12:37
Thanks @AlasdairAtKitronik - that's really useful to know.

So it sounds very much like the hardware on your Piano is not liking the 44KHz audio carrier it's getting on the v2...

I'm guessing we don't want to put a whiny/hissy experience to our teachers/kids. In which case I think we have two ways forward:

  - Tweak hardware to be tolerant in next rev (you might need a small filter or swap amp/transistor?). Maybe an opportunity to push a v2 product line?
  - Configure your extension to just use the raw PWM tones as @jaustin described. You won't get the new audio pipeline which is a shame, but should be able to get equivalent functionality to a v1...

**Comment by finneyj** [comment] 2020-11-10 12:41
@AlasdairAtKitronik Just to clarify (sorry if I misunderstood), but is the sounds hissy/whiny even when sound is played, or only when there's silence? can you tell?

**Comment by AlasdairAtKitronik** [comment] 2020-11-10 12:50
@finneyj The audio carrier theory makes sense - we'll need to have a think about things at Kitronik.

When the micro:bit starts up, there is no hiss/whine, but as soon as one audio action takes place, the background sound is always there, even when other tones are playing.

**Comment by finneyj** [comment] 2020-11-10 12:52
Thanks @AlasdairAtKitronik - really useful to know.

**Comment by AlasdairAtKitronik** [comment] 2020-11-13 14:30
I've been doing some more investigating of this noise, and discovered it's not isolated to the Piano, I can hear the audio hissing on another product which uses the same speaker. 
I used a scope to measure across the speaker, and also the direct output from the micro:bit - not plugged into anything. These were measured after a micro:bit audio block had been used and correctly played a single tone. 

This is the measurement across the speaker, showing a 64Hz signal:
![20201113_125712](https://user-images.githubusercontent.com/36475405/99082017-870fbe00-25bb-11eb-85ab-63f3d14d1b27.jpg)

This is the measurement directly across micro:bit Pin 0 and GND, showing an 85Hz signal:
![20201113_125157](https://user-images.githubusercontent.com/36475405/99082391-00a7ac00-25bc-11eb-8d6b-76f9e0b9bf83.jpg)

I think it's these signals that I'm hearing on the speaker, as they're definitely low frequency tones. 
@finneyj @jaustin Do you know why these signals are present?

**Comment by finneyj** [comment] 2020-11-13 15:02
Hi @AlasdairAtKitronik 

Well that is interesting. TBH, I have no idea how you would get that... or in fact, how/why it would be different on the speaker and P0... or in fact, why you wouldn't be able to hear this on headphones.

Can you share precisely the code you were running??

**Comment by finneyj** [comment] 2020-11-13 15:07
@AlasdairAtKitronik One interesting factoid is that the mixer produces 16bit wide 44KHz samples using 512 byte DMA buffers... if you do the sums, that means the the DMA buffer will flip every 5.8ms... 

Which looks mighty suspiciously close to the period of your waveform on P0 there, don't you think??

**Comment by finneyj** [comment] 2020-11-13 16:01
Hmmm... Just tried this C++ code in CODAL, and I can't repro what you're seeing here. I see a 50% duty cycle square wave, but at 44khz, which is what I would expect:

```
int 
main()
{
    uBit.init();

    uBit.audio.soundExpressions.play("happy");

    while(1)
        uBit.sleep(1000);
}
```

![v2audio](https://user-images.githubusercontent.com/11539567/99092740-7108fa00-25c9-11eb-988d-01ceb70a305f.jpg)

**Comment by finneyj** [comment] 2020-11-13 16:34
Hi @AlasdairAtKitronik 

I have a vague idea what might be happening here. Can you humour me and tryL

- Create a brand new project using the latest makecode /beta
- DO NOT add you extension
- play some sound (e.g. "giggle" from v2 sounds is what I used).

What do you hear/see then?

**Comment by AlasdairAtKitronik** [comment] 2020-11-16 08:30
@finneyj Sorry for the slow reply, haven't looked at work stuff over the weekend.
So, this is the exact program I have using to test, and which produced the results I've been talking about and sent scope pics for:
```typescript
input.onButtonPressed(Button.A, function () {
    music.playTone(262, music.beat(BeatFraction.Whole))
})
input.onButtonPressed(Button.AB, function () {
    music.startMelody(music.builtInMelody(Melodies.Dadadadum), MelodyOptions.Once)
})
input.onButtonPressed(Button.B, function () {
    soundExpression.mysterious.play()
})
```
I've always been using the latest makecode /beta, and I haven't been using the piano extension at all - just listening to the output via the speaker on the piano.

I have created this program from scratch again with the latest makecode:
```typescript
input.onButtonPressed(Button.A, function () {
    soundExpression.giggle.play()
})
```
![image](https://user-images.githubusercontent.com/36475405/99228964-46938880-27e5-11eb-973c-e3b80cfaf91e.png)

It still results in the same hiss/whine noise through the speaker (not on the micro:bit buzzer) as before. I also recreated my original test program in the latest /beta, and it's still giving the same results for all the different ways of producing noise from the blocks. I'm afraid I can't do a scope check today, as I'm back to working from home.

**Comment by AlasdairAtKitronik** [comment] 2020-11-16 15:14
@finneyj Some updates after some more testing.
We've now tested this on 3 micro:bit V2s, and on multiple products which use this speaker - the hiss/whine noise can be heard on all of them, following the same pattern as described above.

There are some new discoveries though. On the Piano, power is provided to everything via usb connector on the piano PCB, and power is then delivered to the micro:bit via the edge connector. It is this setup (the normal one for this product), which has resulted in the noise issue. If power is provided to the piano as normal **and** to the micro:bit - via either the micro USB or a battery pack via JST - there is no hiss/whine noise experienced. This was reproduced across multiple micro:bits and products.

If the micro:bit and speaker product are powered from a single source, there is the hiss/whine noise.
If the micro:bit and speaker product are powered from separate sources, there is **no** hiss/whine noise.

If the micro:bit and speaker product are powered from a single source and the hiss/whine noise starts, and then another power source is provided to the micro:bit without a reset, the noise immediately stops. Removing the power source immediately starts the noise again.

**Comment by jaustin** [comment] 2020-11-19 10:08
> If the micro:bit and speaker product are powered from a single source, there is the hiss/whine noise.
> If the micro:bit and speaker product are powered from separate sources, there is no hiss/whine noise.

When you say single source above, do you mean *any* single source, or just the accessory? How much current does the piana draw? Can you power it from the V2 directly or does it need 5V?

If you can get a scope against the VREG line (3V pad) of the micro:bit before and after the hiss starts and ends that would be really helpful. I'd also like to see the two grounds against each other - so, GND (perhaps use the rounded rectangular connector on the side of the back of the micro:bit) and GND on the speaker board. 

Finally, can you please confirm if you can 'destroy' the hiss by writing digital 0 to P0 sometime after using the speaker? 

So, something like this
* Power board on (no hiss expected)
* Make a sound (hiss with sound)
* End sound (hiss expected)
* Digital write 0 to P0 (hiss ???)

**Comment by AlasdairAtKitronik** [comment] 2020-11-19 10:29
> When you say single source above, do you mean _any_ single source, or just the accessory? How much current does the piana draw? Can you power it from the V2 directly or does it need 5V?

By single source, I am referring to powering the Piano via it's normal USB power connection, and the micro:bit being powered via the 3.3V regulator on the Piano and in through the edge connector. The piano requires 5V, so cannot be powered via the micro:bit. I'm pretty sure the combined current draw is 500mA max.

I should be able to do the extra scope stuff tomorrow when I'm in the office - working from home today.

**Comment by finneyj** [comment] 2020-11-19 13:41
Thanks for updating us @AlasdairAtKitronik/

This is very useful analysis. 

I think I'd be looking at:

- ensuring common ground is as good as possible between the micro:bit and your peripheral.
- maybe adding more bulk capacitance across the power rails on the peripheral side. It could be that the amp isn't quite responding fast enough higher frequency drive of audio on the v2?

**Comment by AlasdairAtKitronik** [comment] 2020-11-20 15:51
Back in the office, and have done some more tests with @DaveAtKitronik suggesting some other things.

On the 3V to GND, there's no obvious difference in the noise on the power rail, whether the hiss is happening or not.
Measured the two GNDs next to each other, no potential difference between them.
Digital Write of 0 to Pin0 does stop the humming sound (previously called the hiss/whine), but also appears to permanently stop the any sound coming out of Pin 0 - even if you play a tone again, it only plays on the V2 speaker.

We wondered if it was high input impedance causing spurious noise pickup from some part of the system. 
To test this, we hooked up just the speaker (no extra circuitry, no amplification, no extra boards) across the Pin 0 and GND pins on the micro:bit. It is very quiet, but it is possible to hear the expected tone, and then the humming noise persisting afterwards. You have to really concentrate to hear it, but it is definitely there. 
To test this further, we hooked up a set of in-ear headphones (so I could block out all external noise), and again, whilst concentrating, it was possible to hear the humming noise after the expected tone. 

I know I reported that I couldn't hear it before with headphones, but using the in-ear buds to block out distracting noises meant that it was possible to pick it out.

Please could you confirm that you are able to hear this noise too with headphones across the micro:bit?

**Comment by AlasdairAtKitronik** [comment] 2020-11-20 15:57
Also, it should be noted that this same humming noise can be heard (more quietly) on the Pimoroni Noise:bit.

**Comment by finneyj** [comment] 2020-11-20 16:39
Thanks @AlasdairAtKitronik. Most interesting.

I haven't heard a hum like you describe on headphones, no (which is what I primarily used when developing the audio pipeline), but if I'm honest, my hearing isn't that good... (too many years playing bass guitar in a live rock band). Might best if others could comment/feedback on this one!

I think I'm really curious why the noise seems to go away with independent power supplies on your board. Would you say that the noise is really gone-gone when you did that? vs. quiet like the unpowered speaker?

Also, does it sound like mains noise perhaps? Is it still present under micro:bit battery power?

**Comment by jaustin** [comment] 2020-11-20 19:05
@AlasdairAtKitronik thanks this is really useful. 

<img width="453" alt="image" src="https://user-images.githubusercontent.com/147113/99839671-045ea400-2b63-11eb-840a-c734eda13cd7.png">

I've tried a different set of headphones with this program ^ and I can hear the noise.

Observations @finneyj 
1) I can hear the noise on headphones, until I press A and then it's nice and silent
2) the noise is *worse* on battery than USB

You can use this as a noise toggle.

1. restart, press logo to play a sound
2. Press A to turn of humm
3. Press B to put it back

**Comment by finneyj** [comment] 2020-11-20 19:18
thanks @jaustin  - good repro!

**Comment by AlasdairAtKitronik** [comment] 2020-12-04 13:40
@jaustin @finneyj Any update on this yet?

**Comment by finneyj** [comment] 2020-12-04 15:11
Hi @AlasdairAtKitronik 

Yes - all pulse input tests are looking good now. I'll be tagging this in about 30 mins just after a final set of tests are completed on one of the other software modules.

**Comment by finneyj** [comment] 2020-12-04 16:09
@AlasdairAtKitronik 

I still don't know the cause here I'm afraid - feels like a bit of ground noise being amplified somehow. As an interim measure I put this C++ API in for you: https://github.com/lancaster-university/codal-microbit-v2/commit/4f1573e506f1cb08cf12a35fd7db1a1e6f12692a

You should be able to call that from inside your extension with a bit of C. If you call this:
```uBit.audio.mixer.setSilenceLevel(0.0f);```

It will cause the mixer to drop to a steady 0V output when silence is being generated. You will likely hear a click as sound starts and stops, but I'm afraid I can't do much about that right now. Hope this improves things a bit whilst we keep investigating the root cause.

**Comment by AlasdairAtKitronik** [comment] 2020-12-09 16:56
@finneyj Thanks for putting that API in place. I've been looking at how to implement it, and am struggling a bit. 
It needs to come into action after a note has played, but having looked through the EventBusValues and MusicEvents, there doesn't seem to be an event for an individual tone being played. The closest is this:
```typescript
music.onEvent(MusicEvent.MelodyNotePlayed, function () {
	
})
```
But it only works for full melodies.
How had you envisaged this being called?

**Comment by finneyj** [comment] 2020-12-09 17:00
Hi @AlasdairAtKitronik 

Sorry, no. You just need to call it once - anytime.  it should then automatically start to idle at the level you specify whenever the mixer is generating silence....

So just calling it once in your initialization code with a parameter of zero should be all you need.

**Comment by AlasdairAtKitronik** [comment] 2020-12-09 17:01
Ah, OK, that makes a lot more sense now. Thanks!

**Comment by finneyj** [comment] 2020-12-09 17:14
cool. I have a cunning plan how we might reduce some of the click noise when it enables/disables silence that i'll try to put in a later release. I can't make promises I'm afraid, but I'll see what we can do.

**Comment by AlasdairAtKitronik** [comment] 2020-12-11 14:43
@finneyj Is the initial fix you did in CODAL available in live MakeCode yet? I can't seem to make it work at all.

**Comment by jaustin** [comment] 2021-01-25 15:17
@abchatra any news on a release that will include this?

**Comment by jaustin** [comment] 2021-02-05 15:05
@AlasdairAtKitronik could you please try /stable now that 0.2.24 has gone out to check we can close this once that release goes to Live?

**Comment by jaustin** [comment] 2021-02-09 15:13
@AlasdairAtKitronik and @DaveAtKitronik now that 0.2.24 has been released to Live, the silence API should be there in Live for you. Please can you check this and close the ticket if it works?

**Comment by AlasdairAtKitronik** [comment] 2021-02-10 09:33
@jaustin Unfortunately, the piano now doesn't work at all with V2 micro:bit - either with or without the silence API - there is zero functionality. It still works completely as expected with V1 micro:bit, so something else must have changed.

**Comment by microbit-carlos** [comment] 2021-02-10 09:52
Is the problem with sound or with the touch sensor as well? Can you print something on the display based on the touch input?

**Comment by AlasdairAtKitronik** [comment] 2021-02-10 10:22
@microbit-carlos It's the touch sensor as well, no response at all

**Comment by AlasdairAtKitronik** [comment] 2021-02-22 14:42
@microbit-carlos @microbit-mark @jaustin 
Is there any update on whether this has been fixed?

**Comment by finneyj** [comment] 2021-02-22 17:19
@AlasdairAtKitronik 

FYI, I ported your driver to C++ last week for testing. I could repro the bug there. i think it was caused by the unusual stream of repeated start i2C transactions on it. After some I2C patches, I had it working cleanly against master branch of codal-microbit-v2 and codal-nrf52.

**Comment by AlasdairAtKitronik** [comment] 2021-02-23 09:52
Right, so are there some changes I need to make to how I'm doing the I2C?

**Comment by finneyj** [comment] 2021-02-23 12:49
I don't think so @AlasdairAtKitronik - I've updated the I2C driver to be more tolerant, so your code should work ok when makeCode pulls through the next CODAL release.

**Comment by microbit-carlos** [comment] 2021-03-18 20:10
@AlasdairAtKitronik the latest CODAL has been added to this version of the editor: https://makecode.microbit.org/stable 

It'd be great if you could test it to confirm if it has resolved the issues?

**Comment by abchatra** [comment] 2021-03-25 21:56
Fixed

**Closed by abchatra** 2021-03-25 21:56 UTC
Labels: Music, codal, v2hardware

**Comment by microbit-carlos** [comment] 2021-03-26 09:21
@AlasdairAtKitronik would you be able to retest with https://makecode.microbit.org/stable, it'd be great to get a final confirmation that this is fully fixed.
