### ISSUE TITLE
Can't load any packages

### ISSUE THREAD

**Issue by Equiphract** [Microsoft/pxt-microbit#1197] opened 2018-09-10 07:52 UTC
Whenever I try to add a package to a project it seems like it's loading something as the block code appears semi transparent but after it changes to solid colours again no new package is added.

I tried using the editor through Google Chrome (68.0.3440.106) and Firefox (60.1.0esr). It didn't work in any of those browsers. I am using Windows 10 Enterprise.

I tried adding projects through the blocks menu and the options menu, same behaviour.

This bug is not only happening on **https://makecode.microbit.org/** but also on **https://makecode.calliope.cc/** (didn't test any other sites).

![unbenannt2](https://user-images.githubusercontent.com/31915427/45283663-c1aed500-b4de-11e8-98c1-96e5e1901c5c.PNG)
This is what appears in the browser console in Firefox when trying to add the neopixel package.

EDIT: I also tested this on different computers in completely different networks, same result.

**Comment by riknoll** [comment] 2018-09-10 17:37
What packages are you trying to add? Can you copy the `pxt.json` in the project after you add the package?

To get the `pxt.json`: 
In the gearwheel go to project setttings and then click "Edit settings as text"

**Comment by riknoll** [comment] 2018-09-10 18:30
I see you mention the Neopixel package, how are you adding it? Just clicking on the card for the package or adding a specific version?

**Comment by Equiphract** [comment] 2018-09-11 07:14
> What packages are you trying to add? Can you copy the pxt.json in the project after you add the package?
> 
> To get the pxt.json:
> In the gearwheel go to project setttings and then click "Edit settings as text"

Here is the pxt.json, it seems like it has added the package after all but it's still not showing in the blocks menu.
```json
{
    "name": "Ohne Titel",
    "dependencies": {
        "core": "*",
        "radio": "*",
        "neopixel": "github:microsoft/pxt-neopixel#v0.6.8"
    },
    "description": "",
    "files": [
        "main.blocks",
        "main.ts",
        "README.md"
    ]
}
```
> I see you mention the Neopixel package, how are you adding it? Just clicking on the card for the package or adding a specific version?

I'm adding the package by scrolling down the blocks menu, clicking on the "add package" button and then I click on the neopixel card.

**Comment by Equiphract** [comment] 2018-09-11 07:40
Ok so I changed the following line in pxt.json
```json
"neopixel":` "github:microsoft/pxt-neopixel#v0.6.8"
```
to 
```json
"neopixel": "github:microsoft/pxt-neopixel#v0.6.7"
```
and now it works both in https://makecode.calliope.cc/ and https://makecode.microbit.org/.
Seems like it's a problem with the newest version.

**Comment by riknoll** [comment] 2018-09-11 18:28
Thanks for posting those errors; the issue is that we are currently upgrading our editor (see [makecode.microbit.org/beta](https://makecode.microbit.org/beta)) and it looks like our add package dialog is fetching the version for the new editor instead of the old. @pelikhan do we have a fix for this while we're transitioning between editors?

**Comment by pelikhan** [comment] 2018-09-11 18:42
Math.idiv should exist on v0...

**Comment by riknoll** [comment] 2018-09-11 20:16
Oh, it's a localization bug. I can repro when I set my language to German

**Comment by riknoll** [comment] 2018-09-12 17:35
Fixed for micro:bit, still broken for Calliope. @pelikhan we need to add Math.idiv and the new random to Calliope

**Comment by riknoll** [comment] 2018-09-12 18:34
Closing in favor of https://github.com/Microsoft/pxt-calliope/issues/29

**Closed by riknoll** 2018-09-12 18:34 UTC
Labels: bug, localization
