### ISSUE TITLE
Error appears when switching to python editor

### ISSUE THREAD

**Issue by KellyLuo1** [microsoft/pxt-microbit#2855] opened 2020-04-20 03:31 UTC
**Describe the bug**
Error appears when switching to python editor

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Open a finished project
3.Switch to python editor

**Expect behavior**
Succeed to switch to python editor and no error appears.

**Actual behavior**
Error appears when switching to python editor.
![Error](https://user-images.githubusercontent.com/58197774/79711272-f8bfac00-82f9-11ea-8e13-766cc529ee9c.gif)

**Additional context**
1.OS: Windows(rs6), iPad
2.makecode.microbit.org version: 2.3.16
3.Microsoft MakeCode version: 5.37.27

**Comment by pelikhan** [comment] 2020-04-20 04:03
Looks related to https://github.com/microsoft/pxt-microbit/issues/2837

**Comment by abchatra** [comment] 2020-04-20 17:15
Duplicate of 2837

**Closed by abchatra** 2020-04-20 17:15 UTC
Labels: bug, next-release
