### ISSUE TITLE
Should have a placeholder image for extensions with no image

### ISSUE THREAD

**Issue by riknoll** [microsoft/pxt-microbit#4583] opened 2022-04-26 21:22 UTC
Instead of showing an error, let's make a nice placeholder:

<img width="460" alt="Screen Shot 2022-04-26 at 2 21 06 PM" src="https://user-images.githubusercontent.com/13754588/165394574-b7818bb2-c72c-4d54-b700-b17105e8c936.png">

**Comment by aznhassan** [comment] 2022-04-26 21:23
This is a duplicate of #4570

**Closed** 2022-04-26 21:24 UTC
Labels: enhancement, extension
