### ISSUE TITLE
"spawn projectile (primed tnt)" spawns ladders instead

### ISSUE THREAD

**Issue by darzu** [Microsoft/pxt-microbit#1936] opened 2019-03-22 19:26 UTC
**Describe the bug**
When using the "spawn projectile (primed tnt)" block, instead ladders are spawned

**To Reproduce**
1. Go MakeCode in Minecraft:EE
2. Add these blocks:
![image](https://user-images.githubusercontent.com/6453828/54848074-8c324200-4ce0-11e9-9d81-86897d2023db.png)
3. Notice that ladders are spawned above your head

**Expected behavior**
TnT should be spawned

**Screenshots**
![tnt-spawns-fence](https://user-images.githubusercontent.com/6453828/54848224-124e8880-4ce1-11e9-87e7-dda790b3e0cc.gif)

**Desktop (please complete the following information):**
 - Mac OS
![image](https://user-images.githubusercontent.com/6453828/54848258-26928580-4ce1-11e9-9980-dfa0c1b6c593.png)

**Comment by darzu** [comment] 2019-03-22 19:28
https://makecode.com/_EMkEkoRVoKkp

Using beta version

**Comment by abchatra** [comment] 2019-03-22 20:29
This is by design. You need spawn the mob and not place it. Both are numbers so you can put one inside other. Something we can't handle today.

**Comment by abchatra** [comment] 2019-03-22 20:29
Closing as won't fix

**Comment by abchatra** [comment] 2019-03-22 20:30
Also please file on Minecraft repo.

**Closed by abchatra** 2019-03-22 20:29 UTC
