### ISSUE TITLE
recording extension: on loud/quiet events not triggering

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#5133] opened 2023-05-12 16:59 UTC
**Describe the bug**
It looks like the extension deactivates the microphone and the loud/quiet events are not triggered when the micro:bit is idle and there is a loud sound.

**To Reproduce**
1. https://makecode.microbit.org/beta
2. Load the recording extension
3. Add the following programme
4. Download the programme to the micro:bit and make a loud noise

<img width="472" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/29712657/43ffb6e5-3d5c-49ef-a29e-91eedfbf992f">

```ts
input.onButtonPressed(Button.A, function () {
    record.startRecording()
})
input.onSound(DetectedSound.Loud, function () {
    basic.showIcon(IconNames.Heart)
})
input.onButtonPressed(Button.B, function () {
    record.playAudio()
})
input.onSound(DetectedSound.Quiet, function () {
    basic.showIcon(IconNames.SmallHeart)
})
```

**Expected behavior**
To make a loud noise and see the large heart on the display.

**Screenshots**
Already added

**micro:bit version (please complete the following information):**

V2.00

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

makecode.microbit.org version:  [5.1.26](https://github.com/Microsoft/pxt-microbit/releases/tag/v5.1.26)
Microsoft MakeCode version:  [8.6.33](https://github.com/Microsoft/pxt/releases/tag/v8.6.33)
microbit runtime version:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)
codal-microbit-v2 runtime version:  [v0.2.50](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.50)

**Comment by srietkerk** [comment] 2023-05-12 21:40
This is not because of the extension, but rather the recent CODAL updates in general. If you do a simple program like the following in beta, you will have the same problem that you describe.

<img width="190" alt="image" src="https://github.com/microsoft/pxt-microbit/assets/49178322/a7f69c4b-e0f1-4c47-8969-9bb11e41a9e0">

This seems to be a duplicate of this issue: https://github.com/microsoft/pxt-microbit/issues/5048

**Closed** 2023-05-23 23:37 UTC
Labels: bug, P2, record
