### ISSUE TITLE
Ring Tone does not allow typed input

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#620] opened 2018-02-02 13:10 UTC
micro:bit-support:4155

When clicking in the value field for the Ring Tone Block, the keyboard note selector covers the input box.

![image](https://user-images.githubusercontent.com/31242877/35734817-4eb3829c-081a-11e8-88bf-8632cf227aee.png)

I am informed that it used to be the case that you were able to input the tone frequency

![image](https://user-images.githubusercontent.com/31242877/35734829-57f727c8-081a-11e8-930c-f8e056d21835.png)

The unit is also indicated as (Hz). If the musical keyboard is the default method of selecting a tone and covering the input field is deliberate, 'Hz' ought to be changed to 'note'.

**Comment by pelikhan** [comment] 2018-02-15 18:10
Looks like a blockly regression.

**Comment by abchatra** [comment] 2018-02-15 19:16
@samelhusseini  this seems like a regression from new blockly. Can you take a look?

**Comment by samelhusseini** [comment] 2018-02-15 19:28
Yep looking.

**Comment by pelikhan** [comment] 2018-02-16 15:44
Fixed in beta.

**Closed by pelikhan** 2018-02-16 15:44 UTC
Labels: P1, bug
