### ISSUE TITLE
makecode that worked for v1.5 and v1.38 a few months ago now gives 020 errors

### ISSUE THREAD

**Issue by stezelMIT** [microsoft/pxt-microbit#4840] opened 2022-08-31 10:41 UTC
**Describe the bug**
The attached hex file:
[microbit-Message_Me_Back_FINAL.hex.zip](https://github.com/microsoft/pxt-microbit/files/9460750/microbit-Message_Me_Back_FINAL.hex.zip)

used to work perfectly a few months ago and now is giving 020 error.  The code is as simple as it gets.
Only when you remove two of the "on Button pressed" blocks the code stops giving 020 error.
What did you change recently in makecode that causes this?  The file size is even different than before.

**To Reproduce**

Try to download the attached hex to a v1.5 v1.38 microbit and get the 020 error

**Expected behavior**
Each button press should lead to yes, no may be in our app
 
**Screenshots**
Add screenshots to help explain your problem. You can copy paste the screenshot in the github report. The .gif screen recording is very useful as well. 

**micro:bit version (please complete the following information):**
v1.5 and v1.38
You can find this information in the lower right hand corner of the back of micro:bit (the side that says BBC micro:bit).
 - Which version of the micro:bit is this relevant to [ EG V1.3, V1.5, V2.0, or specify it's not hardware related ]

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MAC )S 12.4 Monterey
 - Browser [e.g. chrome, safari] Chrome Version 103.0.5060.53 (Official Build) (x86_64)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Samsung Galaxy Tab A is used for the app that talks to microbit

**Additional context**

Quoting my friend Robert  here:
I'm a curriculum developer for the MIT App Inventor team, working on an Internet of Things curriculum for a group of 273 schools in the CoolThink Computational Thinking program. 

We've recently encountered a difficult problem with Microbit, which may impact how many teachers can access our new curriculum. Many of the MakeCode programs we created in March 2022 worked universally for Microbits 1.38, 1. 5, and 2.0. In the few months, when noticed that when we've burned the programs again onto devices, they only work for 2.0 devices. All other devices throw an 020 memory error. Because these are the same MakeCode .hex files and same devices, we have to assume there was an upgrade to the environment that led to this problem. Indeed, the file size of each .hex file has changed between March and July of this year. 

Unfortunately, many of the teachers in our program are under tight budgets. They already have a cache of older Microbits in their classrooms, which should be fine for this project, but they are too under-resourced to buy a duplicate set of 2.0 Microbits in the coming year. 

The deadline for our materials is September 15. Attached is an example MakeCode program in the Internet of Things curriculum. Please contact me with any questions. We're hoping you might help us resolve this technical issue so that the widest variety of schools can use our new curriculum. 

All my best, 

Robert

**Comment by martinwork** [comment] 2022-08-31 11:34
Related: https://github.com/microsoft/pxt-microbit/issues/4808

**Comment by abchatra** [comment] 2022-09-02 18:02
Program here: https://makecode.microbit.org/_MFt2HkP7TLKD
This contains bluetooth uart

**Comment by abchatra** [comment] 2022-09-02 18:02
Duplicate of #4808

**Closed by abchatra** 2022-09-02 18:02 UTC
Labels: bug, P2
