### ISSUE TITLE
No help gif about how to disconnect for Edge browser

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4104] opened 2021-05-25 09:51 UTC
**Describe the bug**
No help gif about how to disconnect for **Edge** browser

**Steps to reproduce the behavior**
1.https://makecode.microbit.org/beta#editor
2.Click **. . .** next Download
3.Click **Disconnect**

**Actual behavior**
No help gif about how to disconnect for **Edge** browser
![4](https://user-images.githubusercontent.com/59192069/119477627-b29d0d80-bd81-11eb-9fc2-2bec5781daed.gif)

**Additional context**
1.OS: Windows(rs6)
2.makecode.microbit.org version: 3.1.86
3.Microsoft MakeCode version: 6.13.41

**Comment by abchatra** [comment] 2021-05-25 16:37
Duplicate of https://github.com/microsoft/pxt/issues/8155 and this is Edge bug and we are talking to them.

**Closed by abchatra** 2021-05-25 16:37 UTC
