### ISSUE TITLE
Offline app doesn't load Norwegian translation correctly

### ISSUE THREAD

**Issue by kristianpedersen** [microsoft/pxt-microbit#3397] opened 2020-09-29 08:03 UTC
We're using the .exe version of the offline app at work, in Norwegian (https://makecode.microbit.org/offline-app)

makecode.microbit.org version:  3.0.19
Microsoft MakeCode version:  6.0.19
microbit runtime version:  v2.2.0-rc6

Many parts of the app still show the English translation. Even on my machine that's connected to the web, the translations don't load correctly. I've tried re-installing the app.

**Offline app** ("blocks" instead of "blokker", "on start" instead of "ved start", etc.)

![exe](https://user-images.githubusercontent.com/5204369/94528964-6d97fa00-0239-11eb-9002-7c6032734d82.png)

**Web version (everything looks correct):**

![web](https://user-images.githubusercontent.com/5204369/94529076-8ef8e600-0239-11eb-91e3-2fdf2ea7249d.png)

**Comment by jwunderl** [comment] 2020-09-29 17:22
I believe the issue is just that the translations are out of date; currently, the translations are pulled at the time the offline app is built, and none of the built in content is updated when internet connections are available; the reason for this is that the offline app might not be kept exactly up to date with the online editor, so it's possible that new content online will be incompatible with the latest offline app (there's some discussion on this / the behavior might change in the future).

If we release a patch with https://github.com/microsoft/pxt/pull/7482 and https://github.com/microsoft/pxt/pull/7469 then the new electron app will have up to date translations (for now)

**Comment by abchatra** [comment] 2020-11-20 18:53
@jwunderl I still see the issue with the latest release.

**Comment by abchatra** [comment] 2021-02-09 02:09
fixed. please verify.

**Closed by abchatra** 2021-02-09 02:09 UTC
Labels: P2, bug, localization, next-release, offline, pending release
