### ISSUE TITLE
Delete all blocks doesn't work in app

### ISSUE THREAD

**Issue by Jaqster** [microsoft/pxt-microbit#1251] opened 2018-09-14 21:57 UTC
In the Windows 10 app, the right-click Workspace 'Delete all blocks' command doesn't work.

**Comment by abchatra** [comment] 2018-09-14 23:36
This is not a regression. Blocks are not able to delete in v0 as well. We should investigate.

**Comment by abchatra** [comment] 2018-09-14 23:36
I do believe this is because of inability to pop up the are you sure dialog.

**Comment by pelikhan** [comment] 2019-06-04 15:26
We should not be using the native js dialog anymore in blockly so this should be fixed by now.

**Comment by abchatra** [comment] 2020-03-20 16:54
Closing old windows10 app bugs.

**Closed by abchatra** 2020-03-20 16:54 UTC
Labels: P2, Windows App, bug
