### ISSUE TITLE
Beta Editor - Kitronik packages not appearing after adding from 'Extensions'

### ISSUE THREAD

**Issue by AlasdairAtKitronik** [Microsoft/pxt-microbit#1015] opened 2018-08-01 07:48 UTC
Started trying out the new Beta editor for MakeCode. Attempted to pull in some of our Kitronik packages (all working correctly in the current version of MakeCode), but even though they can be searched for in 'Extensions', they do not appear in the list of usable packages. However, when clicking the 'Explorer' in JavaScript mode, they all appear to be there. Some blocks from the packages can also be found using the 'Search' function. 

Is there going to have to be a new way of defining blocks or packages to make them appear in the new version? 

I am using Google Chrome on Windows 10.

**Comment by microbit-mark** [comment] 2018-08-01 07:58
Can replicate on Mac Firefox ![screen recording 2018-08-01 at 08 55 am](https://user-images.githubusercontent.com/31242877/43508800-d1cf8b72-9568-11e8-97da-134bcec22f7e.gif)

Other approved packages seem to load oka in the menu

Is this relevant to https://github.com/Microsoft/pxt-microbit/issues/877

**Comment by jaustin** [comment] 2018-08-01 08:13
I've just made the same gif as Mark reproducing this, whoops! They also show up in the search and in the Intellisense for the JS editor...

**Comment by riknoll** [comment] 2018-08-04 00:34
I don't think it's related to #877 but it is weird that this is only affecting Kitronik packages

**Comment by riknoll** [comment] 2018-08-06 22:52
Ah, figured it out. V1 filters categories out of the toolbox if they have no blocks and the `kitronik` category has no blocks because every block definition in the package has the attribute `subcategory="something"`. That is, all of the Kitronik blocks are in the sub categories of `kitronik` and not `kitronik` category itself.

We have moved away from using subcategories so I am hesitant to bring back this behavior. @AlasdairAtKitronik I'm guessing the motivation for this was to have multiple Kitronik packages coexist under one category when added to a project. If so, would you consider moving to the new "groups" feature we introduced in V1? Instead of multiple subcategories you get one flyout with labels above each group of blocks:

![image](https://user-images.githubusercontent.com/13754588/43744767-7e51caa6-9990-11e8-8771-caffe5d4e6e1.png)

(see "Conditionals" and "Comparison" in the above screenshot)

**Comment by riknoll** [comment] 2018-08-06 23:00
I'll bring back the old behavior for the sake of backwards compatibility but "groups" is the new thing going forward

**Comment by CleoQc** [comment] 2018-08-07 00:56
Not from Kitronik, but I have to say I <3 the group feature and the labels that show up.

**Comment by KitronikLtd** [comment] 2018-08-07 08:17
@riknoll I guess we can still do a similar splitting up of our packages with the groups just as well as subcategories - what is the new definition syntax?

**Comment by jaustin** [comment] 2018-08-07 11:33
@riknoll having the old behaviour for compat sounds great.

I guess alongside that it would be good to have clear instructions for how to use groups on https://makecode.com/packages/getting-started or similar? That way people can start porting over their packages soon.

**Comment by CleoQc** [comment] 2018-08-07 12:01
`//% group=LineFollower`  
for a while I had both subcategories and groups together, they were compatible. But I reorganised the blocks and no longer use subcategories.

**Closed** 2018-08-07 17:45 UTC
Labels: P1, bug, extensions, v1

**Comment by riknoll** [comment] 2018-08-07 17:48
I've merged the backwards compat changes so everything should work in the next release!

**Comment by KitronikLtd** [comment] 2018-08-08 07:02
@CleoQc @guillaumejenkins @riknoll Thanks all for your help on this issue!
