### ISSUE TITLE
Serial icon in toolbox doesn't show on Chromebook

### ISSUE THREAD

**Issue by livcheerful** [microsoft/pxt-microbit#4536] opened 2022-04-15 18:12 UTC
**Describe the bug**
The icon doesn't show up in the toolbox

**Screenshots**
![image](https://user-images.githubusercontent.com/18712271/163605920-56876e23-5e6e-4532-9a0d-9d8a55f6f6db.png)

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser Chrome

**Comment by abchatra** [comment] 2022-04-15 20:59
Duplicate of https://github.com/microsoft/pxt-microbit/issues/4499

**Closed by abchatra** 2022-04-15 20:59 UTC
