### ISSUE TITLE
Simulator buttons are lost when adding audio

### ISSUE THREAD

**Issue by livcheerful** [microsoft/pxt-microbit#4011] opened 2021-04-23 18:06 UTC
**Describe the bug**
On the small screen on the Pixelbook, when I add melody blocks, the headphone jack appears for the simulator, pushing the simulator controls down. There's no scrollbar on the side to indicate that there are buttons below, and I thought that they were gone :\ 

**Screenshots**
![image](https://user-images.githubusercontent.com/18712271/115911966-9aa13980-a423-11eb-82e9-6704607dfdbd.png)

**Desktop (please complete the following information):**
 - OS: ChromeOS

**Comment by martinwork** [comment] 2021-04-23 18:23
Related: https://github.com/microsoft/pxt-microbit/issues/3150

**Comment by abchatra** [comment] 2021-04-30 17:48
Duplicate of #3150

**Closed by abchatra** 2021-04-30 17:48 UTC
