### ISSUE TITLE
Mac: No sound when running the program in "Guitar"

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4069] opened 2021-05-19 02:58 UTC
**Describe the bug**
**Mac**: No sound when running the program in "Guitar"

**Steps to reproduce the behavior**
1.Navigate to https://makecode.microbit.org/beta#
2.Music------>Guitar----->Show Instructions
3.Click Light Sensor Tone control, Accelerometer Beat control and Pin Press Switch
4.Run the program in the page

**Actual behavior**
**Mac**: No sound when running the program in "Guitar". No sound except for the program that contains "**on button A**" block on, such as this program in https://makecode.microbit.org/projects/guitar/lightsensor
![image](https://user-images.githubusercontent.com/59192069/118749551-51140500-b890-11eb-8cbf-c2f8405a152b.png)

**Additional context**
1.OS: Mac
2.makecode.microbit.org version: 3.1.84
3.Microsoft MakeCode version: 6.13.34

**Comment by Sheila111** [comment] 2021-05-19 06:02
Also happened in **live version**. Also no sound if running the program in **editor**.
![1](https://user-images.githubusercontent.com/59192069/118763419-6a29af80-b8aa-11eb-9168-0451b8d0f6b8.gif)

**Comment by abchatra** [comment] 2021-05-25 05:35
This is duplicate of https://github.com/microsoft/pxt-microbit/issues/3259

**Closed by abchatra** 2021-05-25 05:35 UTC
