### ISSUE TITLE
 "Turtle" code only run about 1 minute on hardware and reset button doesn't work on hardware

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#1908] opened 2019-03-08 08:04 UTC
**Describe the bug**
 "Turtle" code only run about 1 minute on hardware and reset button doesn't work on hardware

**Steps to reproduce the behavior**
1. Navigate to https://makecode.microbit.org/projects/turtle
2. Copy "Spiral" or "Scanner" code to https://makecode.microbit.org/beta#editor (JavaScript editor)
2. Download each example code and copy code to hardware
2. Observe hardware about 1 minute and press reset button

**Expected behavior**
The code should always run on hardware and reset button should 

**Actual behavior**
 "Turtle" code only run about 1 minute on hardware and reset button doesn't work on hardware

**Comment by abchatra** [comment] 2019-03-14 06:42
@Helen09 Does this work on the live site?

**Comment by Helen09** [comment] 2019-03-15 01:49
@abchatra This bug doesn't repro on live site

**Comment by pelikhan** [comment] 2019-03-21 16:06
This bug is probably a duplicate of https://github.com/Microsoft/pxt-microbit/issues/1865 (uses a mutable image)

**Closed** 2019-03-21 17:18 UTC
Labels: P2, bug, device, next-release
