### ISSUE TITLE
It will show a prompt after opening the tutorial “Countdown”

### ISSUE THREAD

**Issue by Sheila111** [microsoft/pxt-microbit#4503] opened 2022-04-12 03:16 UTC
**Describe the bug**
It will show a **prompt** after opening the tutorial “**Countdown**”

**Steps to reproduce the behavior**
1.Nabigate to https://makecode.microbit.org/beta#
2.Tutorials for the new micro:bit(V2) ---->Countdown---->Blocks Start Tutorial

**Expect behavior**
The toolbox just contains **blocks we need**.
![2](https://user-images.githubusercontent.com/59192069/162891545-e7b8131e-78fa-4939-bdf7-6d628c7b7673.gif)

**Actual behavior**
It will show a prompt **“Could not filter tutorial blocks, displaying full toolbox”**  after opening the tutorial “**Countdown**”. And this tutorial  has the **complete toolbox** not only **blocks we need**.
![1](https://user-images.githubusercontent.com/59192069/162872411-88d2b395-3977-45ab-982b-c57e155b471d.gif)
**Prompt**:
![image](https://user-images.githubusercontent.com/59192069/162872363-a89b332d-70e1-4342-9dd8-12c55caf23aa.png)

**Additional context**
1.OS: Windows11
2.makecode.microbit.org version: 4.1.17
3.Microsoft MakeCode version: 7.5.8

**Comment by Sheila111** [comment] 2022-04-12 06:01
It doesn't happen in **live version**

**Comment by kimprice** [comment] 2022-05-06 19:00
Duplicate of #4538, closed by [microsoft/pxt-blockly#394](https://github.com/microsoft/pxt-blockly/pull/394)

**Closed by kimprice** 2022-05-06 19:00 UTC
Labels: bug, P2, tutorial
