### ISSUE TITLE
Music rest block units are potentially misleading

### ISSUE THREAD

**Issue by microbit-robert** [microsoft/pxt-microbit#4658] opened 2022-05-18 15:21 UTC
We have received feedback that the `(ms)` units on the music rest block are potentially misleading when the default selection is `beat`. 

![image](https://user-images.githubusercontent.com/95928279/169074924-c9897298-bb50-4729-a24c-80ed297fe7a2.png)

While `music.beat()` returns a number in ms, this is likely not clear for a lot of users and can lead to confusion.

Should the units be changed to `(beats)` be default?

The units as `(ms)` make sense when the block appears as:

![image](https://user-images.githubusercontent.com/95928279/169075771-f92e7d79-986a-488d-ad2a-292af23ae076.png)

Loosely connected to this issue, it looks as though there should be a space between `rest` and the unit. `beat` does not appear as a plural when selecting a value greater than one:

![image](https://user-images.githubusercontent.com/95928279/169077315-79563b08-de8f-406d-aa83-1ed1293dc48c.png)

**Comment by abchatra** [comment] 2023-03-02 17:49
Duplicate of https://github.com/microsoft/pxt-microbit/issues/4843 and will be fixed as part of that bug.

**Closed by abchatra** 2023-03-02 17:49 UTC
Labels: enhancement, apis, music
