### ISSUE TITLE
Using a function called `str` fails when coverting blocks to Python

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#3146] opened 2020-05-22 14:59 UTC
**Describe the bug**
If you create function named `str` in blocks and then switch to  Python and call it, nothing is executed with no error. Switching to blocks works fine

**To Reproduce**
![Kapture 2020-05-22 at 15 58 59](https://user-images.githubusercontent.com/31242877/82681100-2d01f180-9c45-11ea-8ea1-86b27af3d521.gif)

**Expected behavior**
program should run in sim in Python as well as in blocks

**Comment by abchatra** [comment] 2020-05-23 04:27
str is a built-in function in python. This is duplicate of https://github.com/microsoft/pxt-microbit/issues/3145 

We need to handle built-in functions in a special way. Probably by adding a _ when converted to python.

**Closed by abchatra** 2020-05-23 04:27 UTC
