### ISSUE TITLE
Serial icon is missing

### ISSUE THREAD

**Issue by ElizabethRiffle** [microsoft/pxt-microbit#4588] opened 2022-04-26 21:39 UTC
Occurred in beta when testing for extensions

![image](https://user-images.githubusercontent.com/14082525/165396886-a0a10c9f-ff76-402a-97b0-a3fa86add628.png)

**Comment by abchatra** [comment] 2022-04-27 01:30
Duplicate of https://github.com/microsoft/pxt-microbit/issues/4499

**Closed by abchatra** 2022-04-27 01:30 UTC
Labels: extension
