### ISSUE TITLE
Embed share not working in safari

### ISSUE THREAD

**Issue by ashaltu** [Microsoft/pxt-microbit#983] opened 2018-07-27 18:59 UTC
Using the embed code to doesn't work correctly in safari

**To Reproduce**
1. Opne a project and drag some code out
2. Click Share and publish the project
3. Click the dropdown labeled "Embed"
4. Copy code and test how it runs in safari (I used jsfiddle.net)

**Expected behavior**
Depending on the code you copy it should render that correctly

**Desktop:**
 - OS: macOS
 - Browser: safari
 - Version: alpha

**Comment by abchatra** [comment] 2018-07-27 21:54
@ashaltu Can you add a screen shot on what happens?

**Comment by riknoll** [comment] 2018-07-30 20:26
Also, it's not actually related to Safari

**Comment by riknoll** [comment] 2018-07-30 22:35
So the issue is just that we haven't updated the embed URL. I'm marking this as won't-fix because it will be fixed as soon as we move beta to master. In the meantime the fix is to take the embed code and add `/beta` to the source URL

**Closed by riknoll** 2018-07-30 22:35 UTC
Labels: P1, bug, v1
