### ISSUE TITLE
Home page has laggy scrolling on Safari

### ISSUE THREAD

**Issue by darzu** [microsoft/pxt-microbit#1896] opened 2019-03-02 00:28 UTC
**Describe the bug**
The home page of makecode microbit has very laggy scrolling even on high end hardware. It's not laggy on Chrome and some screen sizes on Safari are not laggy.

**To Reproduce**
1. makecode.microbit.org/beta
2. Scroll around the page, notice it is laggy
3. If it's not laggy, try resizing the browser a few times, it should be laggy at some sizes
    You can use Safari's Responsive Design Mode, these red options are laggy:

**Expected behavior**
Scrolling should be smooth. On Chrome and some resolutions it is.

**Screenshots**
![safari-is-laggy-3](https://user-images.githubusercontent.com/6453828/53673864-f6eee100-3c3e-11e9-9336-adb37ff969d6.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3 (18D109)
 - Browser Safari Version 12.0.3 (14606.4.5)
- MacBook Pro 2018, i9, 32GB

**Comment by pelikhan** [comment] 2019-03-12 00:22
We do implement the IntersectionObserver . It looks like it is supported in the latest build? https://caniuse.com/#search=intersectionobserver

**Comment by darzu** [comment] 2019-03-29 16:46
It's really slowing down my whole system:
![image](https://user-images.githubusercontent.com/6453828/55248633-7c6bae00-524a-11e9-8a7c-889083d0199a.png)

Chrome and Teams are unusable while I have safari open to arcade.makecode.com's homepage

**Comment by abchatra** [comment] 2020-03-20 06:46
Closing more than an year old bugs. If this still reproduces please reopen.

**Closed by abchatra** 2020-03-20 06:46 UTC
Labels: P2, browser-compat, bug
