### ISSUE TITLE
MakeCode crashes in iOS

### ISSUE THREAD

**Issue by microbit-mark** [microsoft/pxt-microbit#1927] opened 2019-03-19 09:38 UTC
micro:bit support: 20094

**Describe the bug**
User reports multiple crashes of MakeCode in when using the micro:bit app on iOS, making it frustrating to use in classroom situations.

**To Reproduce**
I've not found a consistent reproducer yet, but for example, trying to remove a variable block caused MakeCode to freeze for me.
![IMG_0010](https://user-images.githubusercontent.com/31242877/54594761-3ed87b00-4a29-11e9-81c8-dffe2390be77.PNG)

User reports that creating an array consistently causes MakeCode to freeze
![IMG_0001](https://user-images.githubusercontent.com/31242877/54594898-8101bc80-4a29-11e9-9a43-f8dd8c35de16.PNG)

Returning to the app and then opening MakeCode again seems to resolve the issue.

**Smartphone (please complete the following information):**
 - Device: iPad Air 2
 - OS: 12.1.4
 - Browser: in app browser/safari
 - App Version 3.0.2
- micro:bit MakeCode version 1.2.13

I don't see any info under /Library/Logs/CrashReporter/ when I sync the device. Do we have any telemetry that would help us here @abchatra @martinwork

**Comment by martinwork** [comment] 2019-03-19 11:16
Thanks @microbit-mark . The iOS app hasn't crashed. I can't spot anything helpful in the iOS logs.

I can make it freeze in Safari too (iPad Air, iOS 11.4.1), by creating an array of text and trying to rearrange the items (no neopixels required). I post a screenshot.

**Comment by martinwork** [comment] 2019-03-19 11:19
![IMG_0196](https://user-images.githubusercontent.com/989126/54602169-d72a2c00-4a38-11e9-94be-d228e5b7e89b.png)

**Comment by martinwork** [comment] 2019-03-19 11:32
I can't make it freeze in macOS Safari or Windows Chrome.

**Comment by martinwork** [comment] 2019-03-19 14:05
It can freeze while moving a simple variable or text block. I get the impression that it is much easier to freeze with a small block. Testing in Safari with MakeCode beta.

![IMG_0198](https://user-images.githubusercontent.com/989126/54611878-b91bf600-4a4f-11e9-8b64-46b402419e11.png)

**Comment by microbit-mark** [comment] 2019-03-19 15:42
@abchatra see comments. This reproduces in iOS Safari as well as in the app. Building an array seems to be a good reproducer

**Comment by microbit-mark** [comment] 2019-03-21 11:24
User has tested again and managed to retrieve the crash report. Image is of program that triggered this
[com.apple.WebKit.WebContent-2019-03-18-143647.crash.zip](https://github.com/Microsoft/pxt-microbit/files/2991777/com.apple.WebKit.WebContent-2019-03-18-143647.crash.zip)
![IMG_0004](https://user-images.githubusercontent.com/31242877/54749200-bfcf7800-4bcb-11e9-91bb-b3d04fc1fb59.PNG)

**Comment by martinwork** [comment] 2019-03-22 10:51
The crash log predates this issue. It doesn't mention micro:bit, so maybe it's a Safari crash? I can't make anything crash when MakeCode freezes and I don't see any crash log generated.

From Apple: "The exception code 0xdead10cc indicates that an application has been terminated by the OS because it held on to a file lock or sqlite database lock during suspension. If your application is performing operations on a locked file or sqlite database at suspension time, it must request additional background execution time to complete those operations and relinquish the lock before suspending."

**Comment by microbit-mark** [comment] 2019-03-26 15:12
@abchatra can you look at ios crash logs and tag for next release

**Comment by jwunderl** [comment] 2019-04-16 01:34
All of the crashes listed in this thread should now be fixed with the current [beta](https://makecode.microbit.org/beta) release (v1.4.5), which contains https://github.com/Microsoft/pxt-blockly/pull/230. Thanks for the great examples that helped narrow it down!

**Comment by microbit-mark** [comment] 2019-05-07 12:55
User reports another crash in beta editor on safari, but reports that it behaves for a longer time than previously. This is the code that freezes the editor.

![IMG_0010(1)](https://user-images.githubusercontent.com/31242877/57300881-a0cf6b80-70cf-11e9-83ee-e949f41ba475.PNG)

**Comment by martinwork** [comment] 2019-05-07 13:22
I have entered that code, to make it easy to test. Here it is:
[microbit-ios-safari-crash.zip](https://github.com/microsoft/pxt-microbit/files/3152802/microbit-ios-safari-crash.zip)

@microbit-mark This issue is closed.

**Comment by martinwork** [comment] 2019-05-07 13:27
Is this just in Safari? How to create the problem?

**Comment by microbit-mark** [comment] 2019-05-07 13:31
I asked the user to test in makecode.microbit.org/beta in safari, so yes just in Safari on iOS at present. @jwunderl Can you check this example against your recent fixes?

**Comment by jwunderl** [comment] 2019-05-07 17:31
@microbit-mark I played around with the code you described that crashed for the user (ended up with https://makecode.microbit.org/_LDyiVhVRYEXf loaded into /beta) in the xcode simulator for a while and haven't able to reproduce a crash, but I'm going to re-open this until I can test it on hardware later this week to confirm

**Comment by jwunderl** [comment] 2019-05-09 18:11
Okay, I tested quite a bit on [beta](https://makecode.microbit.org/beta) with those fixes on hardware, and can't reproduce any crashes (tested with both the sample that crashed for them, and with it duplicated to about ~150 blocks). Do we have any more information on the model of iPad it occurs on / confirmation that it occurred on /beta?

**Closed** 2019-05-16 16:32 UTC
Labels: P2, bug, from micro:bit support, next-release
