### ISSUE TITLE
Music blocks silent on alpha editor.

### ISSUE THREAD

**Issue by xmeow** [Microsoft/pxt-microbit#942] opened 2018-07-09 04:58 UTC
All music blocks won't output any sound on Alpha editor after downloading the hex to microbit, but works fine in simulator. 

It is also strange that `pins.analogPitch` works which implement the music blocks.

**Comment by abchatra** [comment] 2018-07-10 16:20
@xmeow this is a nice find. 

Following code plays gibberish in alpha, but plays fine in the live editor.
```
music.beginMelody(music.builtInMelody(Melodies.Dadadadum), MelodyOptions.ForeverInBackground)
```

**Comment by riknoll** [comment] 2018-08-01 18:14
Update: The issue is actually in `parseInt()` which the melody blocks use. It always returns NaN on the hardware and it's messing up the parsing of the melody strings

**Comment by riknoll** [comment] 2018-08-01 20:27
Will be released soon

**Closed** 2018-08-01 20:26 UTC
Labels: Music, P1, bug, v1
