### ISSUE TITLE
Melody block in conditional loop has opposite effect to expected

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1567] opened 2018-11-01 09:40 UTC
support-ticket: 18283

**Describe the bug**
If you place a melody playing forever in a loop with a conditional that should trigger the melody based on a parameter like light level, the audio appear to play in opposite to the condition.

**To Reproduce**
1. Go to https://makecode.microbit.org/_2LDRKyEMy0Dv
2. move the light level in the simulator
3. hear the melody when the condition is not true

**Expected behavior**
The melody should play forever when the condition is true.

**Screenshots**
Another example shows a heart and plays a melody:

<img width="924" alt="fd85a66d-9458-4627-8361-b93b84d0d99e" src="https://user-images.githubusercontent.com/31242877/47844264-e1b19500-ddb9-11e8-8fd1-bfcbcf315ec3.png">

**Additional context**
I can see why this code may not give the expected results as the forever loop means that the melody playing forever is triggered on each iteration and then plays hwhen the consition is not true, but this is a confusing experience for the user. This is also the behaviour on the hardware.

Would it be possible to create a stop melody block, equivalent to 

https://support.microbit.org/a/solutions/articles/19000082590

**Comment by jaustin** [comment] 2018-11-01 11:20
This also shows the issue quite well
https://makecode.microbit.org/_DVVe4KCga7F1

![image](https://user-images.githubusercontent.com/147113/47849009-17f61100-ddc8-11e8-955b-d42662681ed6.png)

As it starts, light level is 128 - no tone
If I drop the light level below 80, tone starts playing 
When I move it back above 80, tone has a quick blip but starts playing again (Instead I think it should stop and NOT resume)

**Comment by abchatra** [comment] 2018-11-01 17:46
@jaustin Your bug is dupe of https://github.com/Microsoft/pxt-microbit/issues/805

**Comment by abchatra** [comment] 2018-11-01 17:48
I can't repro the original bug. When you drag the light level below 80 I hear the music otherwise not. @microbit-mark can you repro?

**Comment by microbit-mark** [comment] 2018-11-02 10:10
The code in https://makecode.microbit.org/_PbcHX8Upp5iJ uses '>' so you should hear music above 80 and otherwise not. Right?

**Comment by martinwork** [comment] 2018-11-02 11:16
I guess as long as the condition is true, the melody is repeatedly restarted, so it never gets going. When the condition becomes false, the melody is left in peace.

With the forever loop, a flag variable can be used to know when the condition **becomes** true. As there is no "stop melody" block, it's necessary to use "once" mode for the melody. The code below uses the same flag variable to enable the melody to be restarted. 

https://makecode.microbit.org/_Ki1b4AUuTVD2

**Comment by abchatra** [comment] 2018-11-02 17:19
if you start the melody forever you will hear it forever. This is by design.

**Closed by abchatra** 2018-11-02 17:19 UTC
Labels: Music, from micro:bit support, needs additional information

**Comment by microbit-mark** [comment] 2018-11-13 14:56
Do you not think this is a confusing experience though @abchatra? Would a 'stop melody' block not be more satisfactory?

**Comment by pelikhan** [comment] 2018-11-13 15:18
We could have a stop melody block.

**Comment by pelikhan** [comment] 2018-11-13 15:21
Foreground, background or both I guess.

**Comment by pelikhan** [comment] 2018-11-13 15:22
We can have a drop down.

**Comment by abchatra** [comment] 2018-11-13 15:43
I like stop melody. @microbit-mark Is it possible to open an feature request issue for stop melody?
