### ISSUE TITLE
randint() not random when bluetooth enabled

### ISSUE THREAD

**Issue by Amerlander** [microsoft/pxt-microbit#5409] opened 2023-11-17 16:53 UTC
**Describe the bug**
When pxt is set to have bluetooth anabled the randint() block always produces the same number. Regardless of v1 or v2.

**To Reproduce**
1. Go to https://makecode.microbit.org
2. Add bluetooth extension
3. Set code to `basic.showNumber(randint(0, 9))`
4. See every time the microbit starts, the same number (one) is displayed

Alternative check this shared project where ble was enabled without loading the bluetooth extension: https://makecode.microbit.org/S91179-28567-56186-10264

**Expected behavior**
I expect the microbit to show a random number that is not predictable.

**micro:bit version (please complete the following information):**
Tested on 1.3, but happens on v1 and v2 afaik.

**Additional context**
On v1 the seedrandom function checks if ble is enabled. If so it tries to use nrf functions for generating a seed and if that fails it is a fix seed. On v2 it is always a fix seed if ble is enabled: https://github.com/lancaster-university/microbit-dal/blob/602153e9199c28c08fd2561ce7b43bf64e9e7394/source/core/MicroBitDevice.cpp#L340

The init function cals `seedrandom()`: https://github.com/lancaster-university/microbit/blob/1d1baa561f82ab0d16d1916b0026955c67d95e74/source/MicroBit.cpp#L118C18-L118C18
But since it gets called before ble is started, it should not matter what value in `BLE_ENABLED` is set.

- I tried to reproduce this error by enabling bluetooth in the microbit samples, but I was not able to reproduce it. I always get random numbers on the samples.
- I tried to replace the static seed fall back with random numbers generated by the sensors, but that still fails.
- `randint()` is [defined in pxt](https://github.com/microsoft/pxt/blob/9ef1988d50f506cdd757c9318ef18360ad264f9d/libs/pxt-common/pxt-core.d.ts#L419), but I didn't figure out how this actually calls the microbit random number functions. Since I was not able to reproduce this issue in the samples, I wonder if there is something on the pxt side I'm missing.

**Comment by abchatra** [comment] 2023-11-21 18:06
@carlosperate @JohnVidler

**Comment by abchatra** [comment] 2024-02-13 18:50
I can reproduce the bug on v2 hardware. The sequence of numbers are always 1,7,8 etc when the hardware is reset and random number is generated on button A pressed.

https://makecode.microbit.org/_EaXWh9CzjFWp

**Comment by microbit-carlos** [comment] 2024-02-15 11:27
@Amerlander would you be able to provide a C++ example that replicates the issue in CODAL? that will help us replicating it and debugging it.

**Comment by Amerlander** [comment] 2024-02-15 11:54
@microbit-carlos unfortunately no, that's why I think this is a microbit-pxt and not a DAL/CODAL issue, as mentioned in my initial post:
> * I tried to reproduce this error by enabling bluetooth in the microbit samples, but I was not able to reproduce it. I always get random numbers on the samples.

It produces non-random ints, when `"MICROBIT_BLE_ENABLED"` is set to `1` in `microbit-pxt`, the same program in C++ is working fine.

The code, that _should_ - **but actually doesn't** - replicate this issue in CODAL would be:
```cpp
#include "MicroBit.h"

MicroBit uBit;

int main()
{
    uBit.init();
    int randomInt = uBit.random(9);
    uBit.display.print(randomInt);
}
```

```json
{
    "target": {
        "name": "codal-microbit-v2",
        "url": "https://github.com/lancaster-university/codal-microbit-v2",
        "branch": "master",
        "type": "git"
    },
    "config":{
        "MICROBIT_BLE_ENABLED" : 1
    }
}
```

**Comment by microbit-carlos** [comment] 2024-02-15 12:33
Thanks @Amerlander!

Would adding this code to the CODAL example make a difference?
https://github.com/microsoft/pxt-microbit/blob/53e49a9ec58a5c5b3b9214d4898298ef1dac7662/libs/core/codal.cpp#L52-L57

**Comment by microbit-carlos** [comment] 2024-02-15 13:39
> * `randint()` is [defined in pxt](https://github.com/microsoft/pxt/blob/9ef1988d50f506cdd757c9318ef18360ad264f9d/libs/pxt-common/pxt-core.d.ts#L419), but I didn't figure out how this actually calls the microbit random number functions. Since I was not able to reproduce this issue in the samples, I wonder if there is something on the pxt side I'm missing.

@abchatra I couldn't easily find the `randint()` implementation either, could somebody point to how this function is implemented? As @Amerlander has commented, it might be an issue in the pxt side.

**Comment by Amerlander** [comment] 2024-02-15 14:27
> Would adding this code to the CODAL example make a difference?

Yes. Using this code reproduces the issue, when BLE is enabled and is working when BLE is disabled

main.cpp in microbit-v2-samples:
```
#include "MicroBit.h"

MicroBit uBit;

int main()
{
    uBit.init();
     microbit_seed_random(); 
     int seed = microbit_random(0x7fffffff); 
     DMESG("random seed: %d", seed); 
     uBit.seedRandom(seed); 
     int randomInt = uBit.random(9);
     uBit.display.print(randomInt);
}
```

codal.json that produces random ints:
```
{
    "target": {
        "name": "codal-microbit-v2",
        "url": "https://github.com/lancaster-university/codal-microbit-v2",
        "branch": "master",
        "type": "git"
    },
    "config":{
        "MICROBIT_BLE_ENABLED" : 0
    }
}
```
Changing the Config to enable BLE will always give the same number as first random int:
```
"MICROBIT_BLE_ENABLED" : 0
```

**Comment by Amerlander** [comment] 2024-02-15 18:24
Uncommenting the line `microbit_seed_random();` in `libs/core/codal.cpp` solves the issue for me: https://github.com/microsoft/pxt-microbit/blob/53e49a9ec58a5c5b3b9214d4898298ef1dac7662/libs/core/codal.cpp#L53

It seems like if `microbit_seed_random();` is called after BLE is initialized in the main `init()` function, the seed stops being random. Since the `init()` function already calls `microbit_seed_random();` right before starting the BLE service it should not be required to call it in `platform_init()` again.

But I'm not that much into the CODAL functions, so I might be wrong.

**Comment by abchatra** [comment] 2024-08-28 21:01
@microbit-carlos  I am going to assign this bug to you and move to hotfix milestone as the fix seems to be on the codal side.

**Comment by microbit-carlos** [comment] 2024-09-13 15:59
We've been looking into this and @Amerlander is spot-on (thank you btw for the bug report, the debugging and analysis!).

`uBit.init()` already  calls `microbit_seed_random()` and for that reason it is not needed in MakeCodes' `platform_init()`:
https://github.com/microsoft/pxt-microbit/blob/7cc19bb881b1404071a521a3d290ef980eca063a/libs/core/codal.cpp#L53

That being said, calling `microbit_seed_random()` again without an argument should have worked and this is a bug in both CODAL and DAL.
The issue is that when it is called this second time, CODAL is missing the implementation that uses SoftDevice, so we need to add that, and DAL has the implementation but often fails, so we need to update it to retry it.

We'll do a CODAL tag with the fix soon, but realistically it will be a while before we release the next DAL tag. So, I've also created this PR in MakeCode which removes the unnecessary call to `microbit_seed_random()`. Which fixes the issue and has the added value that it will reduce the startup time, as generating a random number can be an expensive operation:
- https://github.com/microsoft/pxt-microbit/pull/5945

**Comment by microbit-carlos** [comment] 2024-10-10 16:13
@abchatra I can confirm that with #5945 this issue has been resolved in https://makecode.microbit.org/stable#editor

**Closed** 2024-10-11 00:53 UTC
Labels: bug, P2, bluetooth, v2hardware
