### ISSUE TITLE
Failing to convert code that is in Getting Started samples Rock Paper Scissors and Compass

### ISSUE THREAD

**Issue by darrenge** [Microsoft/pxt-microbit#149] opened 2016-06-24 22:24 UTC
This code snippet is in Rock Paper Scissors sample and it isn't converting it from code to blocks.

input.onGesture(Gesture.Shake, () => {let item = Math.random(3)})

Repro:
* Getting started -> Rock Paper Scissors 
** Notice - this line is in the sample - input.onGesture(Gesture.Shake, () => {let item = Math.random(3)})
* Copy and paste to "Code" of editor 
* Click on "Show Blocks"
** Get error that it doesn't convert

**Comment by pelikhan** [comment] 2016-06-24 22:31
This is a limitation of the blockly compiler.

**Comment by pelikhan** [comment] 2016-06-24 22:32
We need a better blocks -> TypeScript compiler.

**Comment by darrenge** [comment] 2016-07-21 17:48
Tried this on the notd compiler and still fails. Was hoping this was taken care of since it is a sample in the help

**Comment by thomasdenney** [comment] 2016-07-22 09:33
The issue comes from the round tripping. When converted back to blocks the declaration of `weapon` is moved out into global scope (as are all non-loop variables in blocks), so blocks -> JS compile generates the following, so the comparison fails and therefore you can't enter blocks mode.

```typescript
let weapon = 0
input.onGersture(Gesture.Shake, () => {
    weapon = Math.random(3)
})
```

This bug occurs for **all** variables that are not declared in the global scope:

```typescript
while (true) {
    let x = 0
}
```

A short term solution is to document this as unsupported (@tballmsft  ?) or a longer term solution would be to add support in blockly for scoped variables.

**Comment by thomasdenney** [comment] 2016-07-22 14:29
In the mean time I'm working on some code for the CLI that generates blocks from all the snippets in the documentation, and then generates JS from the blocks to test if it would be possible in the web app.

**Comment by pelikhan** [comment] 2016-07-22 14:30
The “gendocs” command already dumps all the snippets to disk. From there you should be able to apply a round trip to each snippet. GREAT!

**Comment by thomasdenney** [comment] 2016-07-22 14:33
Yep, using gendocs to get the snippets :). Compiling server side is a bit fun because most of the current code for compiling is dependent on client side code, but I'm slowly getting round that.

**Comment by pelikhan** [comment] 2016-07-22 14:55
Ok, please prepare a PR for this change so that we can review them.

**Comment by thomasdenney** [comment] 2016-07-22 16:16
I'm now able to generate the XML in the cloud (using some really nasty hacks at the moment, I'll be able to get around them when I've figured out better ways of using some of the code from the server), which serves as a useful test of gauging how many snippets *could* be rendered (684/877). The next step is to figure out a subset of blockly that I need server side to compile blocks back to JS, as this will then enable me to figure out which of these produce *correct* blocks.

**Comment by thomasdenney** [comment] 2016-07-22 22:43
The numbers are slightly better now that I've fixed some problems in the server side compiler:

```
767 snippets compiled to blocks
110 snippets did not compile to blocks
```

(This *excludes* the trip back to JS, I haven't implemented that server side yet)

**Comment by darrenge** [comment] 2016-08-04 21:14
Two samples in the help that are not covered:
- [ ] Paper Rock Scissors
input.onGesture(Gesture.Shake, () => {
    let weapon = Math.random(3)
    if (weapon == 0) {
        basic.showLeds(`
            # # # # #
            # . . . #
            # . . . #
            # . . . #
            # # # # #
            `)

    } else if (weapon == 1) {
        basic.showLeds(`
            . . . . .
            . # # # .
            . # # # .
            . # # # .
            . . . . .
            `)
    } else {
        basic.showLeds(`
            # # . . #
            # # . # .
            . . # . .
            # # . # .
            # # . . #
            `)
    }
})
- [ ] Compass
basic.forever(() => {
    let degrees = input.compassHeading();
    if (degrees < 45) {
        basic.showString("N");
    } else if (degrees < 135) {
        basic.showString("E");
    } else if (degrees < 225) {
        basic.showString("S");
    } else {
        basic.showString("W");
    }
});

**Comment by mmoskal** [comment] 2016-08-25 09:36
Duplicate of https://github.com/Microsoft/pxt/issues/151

**Closed by mmoskal** 2016-08-25 09:36 UTC
Labels: bug, P1
