### ISSUE TITLE
"Get Started" tutorial's 6th step is not complete

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt-microbit#878] opened 2018-06-20 09:22 UTC
**Repro steps:**
• Navigate to https://makecode.microbit.org/alpha
• Scroll down to the bottom of the Home page
• Click "Get Started!" -> "Start Tutorial" to open this tutorial
• Click this tutorial steps one by one
**Expected result(on beta):**
Every step of this tutorial should be complete
![issue2](https://user-images.githubusercontent.com/23466737/41649472-2cf3cab4-746b-11e8-90f7-c05d63875496.PNG)

**Actual result(on alpha):**
 When clicked to step 6, the tutorial is not complete
![issue1](https://user-images.githubusercontent.com/23466737/41649481-32eab6c6-746b-11e8-84f9-770ea545329b.PNG)

**Comment by Helen09** [comment] 2018-06-20 09:34
The issue also exists in many other tutorials' step
**For example:**
**Flashing Heart 1th step:**
![flashing heart](https://user-images.githubusercontent.com/23466737/41650202-036fe0f4-746d-11e8-967b-6438b9992c9c.PNG)

**Smiley Buttons 2th step & 4th step:**
![smiley buttons](https://user-images.githubusercontent.com/23466737/41650222-0c83435c-746d-11e8-9502-5c79191e4a15.PNG)
![smiley buttons4](https://user-images.githubusercontent.com/23466737/41650238-13241448-746d-11e8-995d-a6ea4de0c612.PNG)

**Coin Flipper 1th step:**
![coin flipper1](https://user-images.githubusercontent.com/23466737/41650243-1b5b412c-746d-11e8-8ea3-8aa100f45387.PNG)

**Comment by samelhusseini** [comment] 2018-06-21 23:03
Fixed in v1. https://github.com/Microsoft/pxt-microbit/pull/885

Root cause: important to have first line of tutorial step be one line. Don't break it for word wrap, otherwise it will be cut into the hint. @ganicke FYI if you ever run into an issue like this.

**Closed by samelhusseini** 2018-06-21 23:03 UTC
Labels: P1, bug, v1
