### ISSUE TITLE
when i declare a *REAL* function the start block contains many grey blocks

### ISSUE THREAD

**Issue by rhubarbdog** [Microsoft/pxt-microbit#1703] opened 2018-12-06 06:43 UTC
**Describe the bug**
I have the need for sub routines and functions which java supports and blocks creates a grey block they function correctly.  It also produces all my let statements in grey blocks they have variable blocks

**To Reproduce**
<a href="https://makecode.microbit.org/_673UXEc3diP6">see these blocks</a>
**Expected behavior**
I expect only function and procedure definitions and calls to have grey blocks

**Desktop (please complete the following information):**
 - OS : Linux Mint 18.2 clone of ubuntu 16.04
 - Browser : firefox
 - Version : 60.0.1

**Comment by abchatra** [comment] 2018-12-07 18:39
Duplicate of https://github.com/Microsoft/pxt-microbit/issues/689
We are working on it.

**Closed by abchatra** 2018-12-07 18:39 UTC
