### ISSUE TITLE
Couldn't find any extensions on MakeCode

### ISSUE THREAD

**Issue by kiate** [microsoft/pxt-microbit#3996] opened 2021-04-22 04:03 UTC
**Describe the bug**
Unable to find all extensions using the search function. Both keywords and GitHub URLs don't work.

**To Reproduce**
Just try to add any extension on MakeCode. It will return "We couldn't find any extensions matching '[extension name]' "

**MakeCode version:**
https://makecode.microbit.org/
https://makecode.microbit.org/beta
https://makecode.microbit.org/v1

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome, Chrome Incognito, Firefox, Edge

**Comment by abchatra** [comment] 2021-04-22 04:52
I can reproduce this bug.

**Comment by abchatra** [comment] 2021-04-22 06:53
Update: We are actively investigating this. Looks like rate limiting from the github at this point of time.

**Comment by abchatra** [comment] 2021-04-22 08:56
This should be fixed now. Apologies!

**Closed by abchatra** 2021-04-22 08:56 UTC
Labels: P1, bug, next-release

**Comment by microbit-mark** [comment] 2021-04-22 08:59
Thanks for the quick fix @abchatra. We had a lot of teachers report this issue.

**Comment by kiate** [comment] 2021-04-22 10:47
Thanks @abchatra !
